'use client';
import React,{useEffect,useState}from'react';
import type{SystemPick}from'../../web/app/SystemBuilderPanel';
import type{Market,Row}from'./mobile-types';
import{category,pct}from'./mobile-types';

const API='http://localhost:4000';
async function request(url:string,init?:RequestInit){const r=await fetch(url,init);const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.message||`${r.status}`);return b}
const post=(url:string,body:unknown)=>request(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});

export function DetailPanels({row,selected,add}:{row:Row;selected:(id:string)=>boolean;add:(pick:SystemPick)=>void}){
  const[tab,setTab]=useState('Esito');
  const[players,setPlayers]=useState<any[]|null>(null),[playerError,setPlayerError]=useState(''),[loadingPlayers,setLoadingPlayers]=useState(false);
  const[value,setValue]=useState<any[]|null>(null),[valueSource,setValueSource]=useState(''),[valueReason,setValueReason]=useState(''),[loadingValue,setLoadingValue]=useState(false);
  const tabs=['Esito','Gol','Team','Risultati','Combinazioni','Marcatori','Value'];
  function choose(name:string){setTab(name);if(name==='Marcatori'&&players===null&&!loadingPlayers){setLoadingPlayers(true);setPlayerError('');void request(`${API}/player-markets?fixtureId=${encodeURIComponent(row.fixture.id)}&competition=SA`).then(x=>setPlayers(x.data||[])).catch(e=>setPlayerError(e.message)).finally(()=>setLoadingPlayers(false))}if(name==='Value'&&value===null&&!loadingValue){setLoadingValue(true);setValueReason('');void request(`${API}/v2/value?fixtureId=${encodeURIComponent(row.fixture.id)}&competition=SA`).then(x=>{setValue(x.data||[]);setValueSource(x.source||'UNAVAILABLE');setValueReason(x.reason||'')}).catch(e=>setValueReason(e.message)).finally(()=>setLoadingValue(false))}}
  const shown=row.markets.filter(m=>category(m)===tab);
  return <><div className="mCats mStickyCats">{tabs.map(x=><button key={x} className={tab===x?'on':''} onClick={()=>choose(x)}>{x}</button>)}</div><section className="mPanel">{tab==='Marcatori'?<Players row={row} players={players} loading={loadingPlayers} error={playerError} selected={selected} add={add}/>:tab==='Value'?<Values rows={value} source={valueSource} reason={valueReason} loading={loadingValue}/>:shown.length?shown.map(m=>{const p=marketPick(row,m);return <div className={'mMarket '+(m.status==='NO_BET'?'off':'')} key={`${m.market}-${m.selection}`}><span><small>{m.market}</small><b>{m.selection}</b><small>Conf. {pct(m.confidence)} · DQ {pct(m.dataQuality)}{m.fairOdds?` · Fair ${m.fairOdds.toFixed(2)}`:''}</small>{m.reason&&<small>{m.reason}</small>}{m.status==='ACTIVE'&&<BetActions pick={p}/>}</span><strong>{m.status==='ACTIVE'?pct(m.probability):'NO BET'}</strong><button aria-label={`Aggiungi ${m.selection}`} disabled={m.status!=='ACTIVE'||selected(p.id)} onClick={()=>add(p)}>{selected(p.id)?'✓':'+'}</button></div>}):<div className="mEmpty">Mercato non disponibile.</div>}</section></>;
}

function Players({row,players,loading,error,selected,add}:{row:Row;players:any[]|null;loading:boolean;error:string;selected:(id:string)=>boolean;add:(pick:SystemPick)=>void}){if(loading)return <p>Caricamento marcatori…</p>;if(error)return <div className="mNotice">{error}</div>;if(!players?.length)return <div className="mEmpty">NO_BET giocatori: lineup o dati insufficienti.</div>;return <>{players.map(player=>{const p:SystemPick={id:`${row.fixture.id}|ANYTIME_SCORER|${player.playerId}`,fixtureId:row.fixture.id,market:'ANYTIME_SCORER',selection:player.selection||`${player.playerName} segna`,eventAt:row.fixture.utcDate,probability:player.probability,confidence:player.confidence,dataQuality:player.dataQuality,fairOdds:player.fairOdds,period:'FT',teamSide:player.teamSide,playerId:player.playerId};return <div className={'mMarket '+(player.status==='NO_BET'?'off':'')} key={player.playerId}><span><small>ANYTIME SCORER</small><b>{player.playerName}</b><small>Conf. {pct(player.confidence)} · DQ {pct(player.dataQuality)} · {player.playerImpact?.role||'ruolo n/d'}</small>{player.status==='ACTIVE'&&<BetActions pick={p}/>}</span><strong>{player.status==='ACTIVE'?pct(player.probability):'NO BET'}</strong><button aria-label={`Aggiungi ${player.playerName} segna`} disabled={player.status!=='ACTIVE'||selected(p.id)} onClick={()=>add(p)}>{selected(p.id)?'✓':'+'}</button></div>})}</>}
function Values({rows,source,reason,loading}:{rows:any[]|null;source:string;reason:string;loading:boolean}){if(loading)return <p>Recupero quote pre-match…</p>;if(!rows?.length)return <div className="mEmpty">{reason||'Value non disponibile: nessuna quota gratuita disponibile.'}</div>;return <>{reason&&<div className="mNotice">{source==='UNAVAILABLE'?'QUOTE NON DISPONIBILI':reason}</div>}{rows.map(x=><div className="mMarket" key={`${x.market}-${x.selection}`}><span><small>{x.market} · {x.bookmaker||'NO BOOKMAKER'}</small><b>{x.selection}</b><small>Fair {x.fairOdds?Number(x.fairOdds).toFixed(2):'—'} · Offerta {x.offeredOdds?Number(x.offeredOdds).toFixed(2):'—'} · EV {x.expectedValue==null?'—':pct(x.expectedValue)}</small></span><strong>{pct(x.probability)}</strong><i>{x.valueStatus}</div>))}</>}
function marketPick(row:Row,m:Market):SystemPick{return{id:`${row.fixture.id}|${m.market}|${m.selection}`,fixtureId:row.fixture.id,market:m.market,selection:m.selection,eventAt:row.fixture.utcDate,probability:m.probability,confidence:m.confidence,dataQuality:m.dataQuality,fairOdds:m.fairOdds,period:m.period,metric:m.metric,operator:m.operator,threshold:m.threshold,outcome:m.outcome}}
function BetActions({pick}:{pick:SystemPick}){const[stake,setStake]=useState('5'),[odds,setOdds]=useState(''),[bookmaker,setBookmaker]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);async function save(mode:'NOT_PLAYED'|'PLAYED'|'SIMULATED'){const s=Number(stake),o=Number(odds);if(!Number.isFinite(s)||s<=0){setMessage('Inserisci uno stake valido.');return}if(mode!=='NOT_PLAYED'&&(!Number.isFinite(o)||o<1.01)){setMessage('Inserisci una quota di esecuzione valida per reale o paper.');return}setBusy(true);setMessage('');try{await post(`${API}/v2/history/bets`,{fixtureId:pick.fixtureId,competition:'SA',market:pick.market,selection:pick.selection,stake:s,odds:mode==='NOT_PLAYED'?undefined:o,bookmaker:bookmaker.trim()||undefined,played:mode==='PLAYED',simulated:mode==='SIMULATED',eventAt:pick.eventAt});setMessage(mode==='PLAYED'?'Singola registrata come realmente giocata.':mode==='SIMULATED'?'Singola registrata in paper trading.':'Prediction salvata come non giocata.')}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}return <details className="executionDetails singleExecution"><summary>Registra singola</summary><div className="form"><label>Stake €<input aria-label={`Stake ${pick.selection}`} type="number" min="0.1" step="0.1" value={stake} onChange={e=>setStake(e.target.value)}/></label><label>Quota esecuzione<input aria-label={`Quota singola ${pick.selection}`} type="number" min="1.01" step="0.01" value={odds} onChange={e=>setOdds(e.target.value)}/></label><label>Bookmaker<input value={bookmaker} onChange={e=>setBookmaker(e.target.value)} placeholder="opzionale"/></label></div><div className="executionActions"><button disabled={busy} onClick={()=>save('NOT_PLAYED')}>Salva</button><button disabled={busy} onClick={()=>save('SIMULATED')}>Paper</button><button className="primary" disabled={busy} onClick={()=>save('PLAYED')}>L’ho giocata</button></div>{message&&<p>{message}</p>}</details>}
