import{buildSystemWithFixed,compatibility,correlation,optimizeSystem,settleMvpMarket,suggestAssistedSystem,type Selection}from'@fps/domain';import{FootballProvider,PredictionApplicationService,type LocalStore}from'@fps/mobile-runtime';
const BASE='http://localhost:4000';
export function installLocalApi(provider:FootballProvider,store:LocalStore){const nativeFetch=window.fetch.bind(window),predictions=new PredictionApplicationService(provider,store);window.fetch=(async(input:RequestInfo|URL,init?:RequestInit)=>{const raw=typeof input==='string'?input:input instanceof URL?input.toString():input.url;if(!raw.startsWith(BASE))return nativeFetch(input as any,init);try{const u=new URL(raw),method=(init?.method||'GET').toUpperCase(),body=init?.body?JSON.parse(String(init.body)):undefined;const value=await route(u.pathname,u.searchParams,method,body,{provider,store,predictions});return json(value)}catch(e:any){return json({message:e?.message||'Local runtime error'},400)}})as typeof window.fetch}
async function route(path:string,q:URLSearchParams,method:string,body:any,c:{provider:FootballProvider;store:LocalStore;predictions:PredictionApplicationService}){
 if(method==='GET'&&path==='/v2/predictions')return c.predictions.predictions(q.get('competition')||'SA',q.get('persist')!=='false');
 if(method==='POST'&&path==='/v2/systems/analyze')return analyze(body?.selections||[]);
 if(method==='POST'&&path==='/v2/systems/build')return buildSystemWithFixed(body.selections,Number(body.k),Number(body.stake),body.fixedIds||[]);
 if(method==='POST'&&path==='/v2/systems/assist')return suggestAssistedSystem({selections:body.selections,minCorrect:Number(body.minCorrect),budget:Number(body.budget),fixedIds:body.fixedIds||[],profile:body.profile||'BALANCED'});
 if(method==='POST'&&path==='/v2/systems/optimize')return optimizeSystem(body.selections,Number(body.budget),body.profile||'BALANCED');
 if(method==='POST'&&path==='/systems/save'){const id=crypto.randomUUID(),record={...body,id,createdAt:new Date().toISOString(),played:false,simulated:false,status:'PENDING',payout:null};await c.store.saveRecord('system',record);return record}
 const exec=path.match(/^\/v2\/history\/systems\/([^/]+)\/execution$/);if(method==='POST'&&exec){const all=await c.store.listRecords('system'),old=all.find(x=>x.id===exec[1]);if(!old)throw new Error('Sistema non trovato');const mode=body?.mode||'NOT_PLAYED',record={...old,played:mode==='PLAYED',simulated:mode==='SIMULATED',bookmaker:body?.bookmaker||old.bookmaker,status:mode==='NOT_PLAYED'?'PENDING':old.status};await c.store.saveRecord('system',record);return record}
 if(method==='GET'&&path==='/v2/history/systems')return filter(await c.store.listRecords('system'),q);
 if(method==='GET'&&path==='/v2/history/bets')return filter(await c.store.listRecords('bet'),q);
 if(method==='GET'&&path==='/v2/history/predictions')return predictionHistory(c.store,q);
 if(method==='POST'&&path==='/settlement/run')return settleAll(c.provider,c.store);
 if(method==='GET'&&path==='/ops/performance')return performance(c.store);
 if(method==='GET'&&path==='/v2/paper/report')return paperReport(c.store,Number(q.get('bankroll')||1000));
 const intel=path.match(/^\/v2\/matches\/([^/]+)\/intelligence$/);if(method==='GET'&&intel)return intelligence(c.provider,intel[1],q.get('competition')||'SA');
 if(method==='GET'&&path==='/player-markets')return{source:'UNAVAILABLE',data:[],reason:'Dati giocatore insufficienti o non disponibili sul piano configurato'};
 if(method==='GET'&&path==='/v2/value')return{source:'UNAVAILABLE',data:[],reason:'Quote bookmaker non disponibili; Value non viene inventato'};
 throw new Error(`Route locale non supportata: ${method} ${path}`)
}
function analyze(selections:Selection[]){const incompatible:any[]=[],correlations:any[]=[];for(let i=0;i<selections.length;i++)for(let j=i+1;j<selections.length;j++){const a=selections[i],b=selections[j];if(compatibility(a,b)==='INCOMPATIBLE')incompatible.push({left:a.id,right:b.id});else{const x=correlation(a,b);correlations.push({left:a.id,right:b.id,...x})}}return{status:incompatible.length?'INCOMPATIBLE':'OK',incompatible,correlations,maxCorrelation:correlations.length?Math.max(...correlations.map(x=>x.score)):0,reason:incompatible.length?'Sono presenti selezioni logicamente incompatibili':undefined}}
async function predictionHistory(store:LocalStore,q:URLSearchParams){const runs=await store.listPredictionRuns(),settlements=await store.listRecords('prediction_settlement'),byKey=new Map(settlements.map(x=>[x.key,x]));const rows=runs.flatMap((run:any)=>(run.markets||[]).map((m:any)=>{const key=`${run.id}|${m.market}|${m.selection}`,s=byKey.get(key);return{id:key,fixture:run.fixture||{competition:run.competition||'SA'},capturedAt:run.capturedAt,modelVersion:run.modelVersion,market:m.market,selection:m.selection,probability:m.probability,confidence:m.confidence,dataQuality:m.dataQuality,fairOdds:m.fairOdds,status:m.status,outcome:s?.outcome||'PENDING'}}));return filter(rows,q)}
async function settleAll(provider:FootballProvider,store:LocalStore){let processed=0,fixturesFetched=0;const cache=new Map<string,any>();const get=async(id:string)=>{if(cache.has(id))return cache.get(id);const r=await provider.result(id);cache.set(id,r);fixturesFetched++;return r};const existing=await store.listRecords('prediction_settlement'),seen=new Set(existing.map(x=>x.key));for(const run of await store.listPredictionRuns()){if(new Date(run.eventAt).getTime()>Date.now())continue;const result=await get(run.fixtureId);if(result.status!=='FINISHED'||result.home==null||result.away==null)continue;for(const m of run.markets||[]){const key=`${run.id}|${m.market}|${m.selection}`;if(seen.has(key))continue;const outcome=settleMvpMarket(m.market,m.selection,{home:result.home,away:result.away,scorers:result.scorers});if(outcome==='UNSUPPORTED')continue;await store.saveRecord('prediction_settlement',{id:crypto.randomUUID(),key,runId:run.id,fixtureId:run.fixtureId,market:m.market,selection:m.selection,probability:m.probability,outcome,verifiedAt:new Date().toISOString(),evidence:result});seen.add(key);processed++}}
 for(const sys of await store.listRecords('system')){if(!sys.played&&!sys.simulated)continue;if(sys.status==='VERIFIED')continue;const selections=[] as any[];let pending=false;for(const s of sys.selections||[]){if(new Date(s.eventAt).getTime()>Date.now()){pending=true;break}const r=await get(s.fixtureId);if(r.status!=='FINISHED'||r.home==null||r.away==null){pending=true;break}const outcome=settleMvpMarket(s.market,s.selection,{home:r.home,away:r.away,scorers:r.scorers});if(outcome==='UNSUPPORTED'){pending=true;break}selections.push({...s,outcome})}if(pending)continue;const byKey=new Map(selections.map(s=>[s.clientKey||s.id,s]));let payout=0;const combos=(sys.combinations||[]).map((combo:any)=>{const legs=(combo.selectionKeys||[]).map((k:string)=>byKey.get(k)).filter(Boolean);const outcomes=legs.map((x:any)=>x.outcome);const status=outcomes.includes('LOSS')?'LOSS':outcomes.every((x:string)=>x==='VOID')?'VOID':'WIN';let mult=1;for(const leg of legs)if(leg.outcome==='WIN')mult*=Number(leg.odds||1);const ret=status==='LOSS'?0:Number(combo.stake||0)*mult;payout+=ret;return{...combo,status,payout:ret}});await store.saveRecord('system',{...sys,selections,combinations:combos,status:'VERIFIED',payout:Number(payout.toFixed(2)),verifiedAt:new Date().toISOString()});processed++}return{processed,fixturesFetched}}
async function performance(store:LocalStore){const settlements=await store.listRecords('prediction_settlement'),usable=settlements.filter(x=>x.outcome==='WIN'||x.outcome==='LOSS'),sample=usable.length,brier=sample?usable.reduce((n,x)=>n+Math.pow(Number(x.probability)-(x.outcome==='WIN'?1:0),2),0)/sample:null,hit=sample?usable.filter(x=>x.outcome==='WIN').length/sample:null;const systems=(await store.listRecords('system')).filter(x=>x.played&&x.status==='VERIFIED'),stake=systems.reduce((n,x)=>n+Number(x.totalCost||0),0),returns=systems.reduce((n,x)=>n+Number(x.payout||0),0),profit=returns-stake;return{modelPerformance:{sample,brierScore:brier,logLoss:null,hitRate:hit,calibrationError:null,calibration:[],byMarket:[],byCompetition:[],byConfidence:[],byModelVersion:[],byPeriod:[]},bettingPerformance:{sample:systems.length,stake,returns,profit,roi:stake?profit/stake:null,yield:stake?profit/stake:null,winRate:systems.length?systems.filter(x=>Number(x.payout)>Number(x.totalCost||0)).length/systems.length:null,averageOdds:null,maxDrawdown:null,systemsVsSingles:{systems:{systems:systems.length,combinations:systems.reduce((n,x)=>n+(x.combinations?.length||0),0)},singles:{sample:0}},byMarket:[],byCompetition:[],byBookmaker:[]}}}
async function paperReport(store:LocalStore,bankroll:number){const systems=(await store.listRecords('system')).filter(x=>x.simulated&&x.status==='VERIFIED'),stake=systems.reduce((n,x)=>n+Number(x.totalCost||0),0),returns=systems.reduce((n,x)=>n+Number(x.payout||0),0),profit=returns-stake;return{bankrollInitial:bankroll,bankrollFinal:bankroll+profit,profit,roi:stake?profit/stake:null,yield:stake?profit/stake:null,maxDrawdown:0,winRate:systems.length?systems.filter(x=>Number(x.payout)>Number(x.totalCost||0)).length/systems.length:null,betsCount:0,systemsCount:systems.length,stakeTotal:stake,incompleteEconomicRecords:0,marketPerformance:[]}}
async function intelligence(provider:FootballProvider,fixtureId:string,competition:string){const[fixtures,standings]=await Promise.all([provider.fixtures(competition),provider.standings(competition)]),f=fixtures.find(x=>x.id===fixtureId);if(!f)throw new Error('Fixture non trovata');const by=new Map(standings.map(x=>[x.teamId,x]));return{statistics:{home:by.get(f.home.id)||null,away:by.get(f.away.id)||null},lineup:{home:{starters:[],bench:[]},away:{starters:[],bench:[]},source:'UNAVAILABLE'},injuries:[],availabilityVerified:false,explanation:['Statistiche squadra acquisite dal provider configurato.','Lineup e indisponibili vengono mostrate solo quando disponibili; nessun dato mancante viene inventato.']}}
function filter(items:any[],q:URLSearchParams){return items.filter(x=>{const status=q.get('status')||q.get('outcome'),mode=q.get('mode'),market=q.get('market'),competition=q.get('competition'),bookmaker=q.get('bookmaker');if(status&&String(x.status||x.outcome)!==status)return false;if(mode==='PLAYED'&&!x.played)return false;if(mode==='SIMULATED'&&!x.simulated)return false;if(mode==='NOT_PLAYED'&&(x.played||x.simulated))return false;if(market&&!String(x.market||'').toLowerCase().includes(market.toLowerCase()))return false;if(competition&&!String(x.competition||x.fixture?.competition||'').toLowerCase().includes(competition.toLowerCase()))return false;if(bookmaker&&!String(x.bookmaker||'').toLowerCase().includes(bookmaker.toLowerCase()))return false;return true})}
function json(v:any,status=200){return new Response(JSON.stringify(v),{status,headers:{'content-type':'application/json'}})}
