import React,{useEffect,useMemo,useState}from'react';
import HistoryDashboard from'../../web/app/HistoryDashboard';
import StatsDashboard from'../../web/app/StatsDashboard';
import SystemBuilderPanel,{type SystemPick}from'../../web/app/SystemBuilderPanel';
import MatchIntelligence from'../../web/app/MatchIntelligence';
import{FilterBar,type FilterState}from'./FilterBar';
import{MatchCard}from'./MatchCard';
import{DetailPanels}from'./DetailPanels';
import type{Market,Row}from'./mobile-types';
import{day,featured,forQuick,pct}from'./mobile-types';

const API='http://localhost:4000',RELEASE='v1.1.0-beta.1';
type Mode='PRESEASON'|'LIVE';
type Tab='Pronostici'|'Partite'|'Sistema'|'Storico'|'Statistiche'|'I miei sistemi'|'Impostazioni';
const initial:FilterState={quick:'Tutti',team:'',scope:'ALL',minP:0,minC:0,minD:0,sort:'TIME'};

async function request(url:string){const r=await fetch(url);const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.message||`${r.status}`);return b}

export default function MobileHome(){
 const[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[bag,setBag]=useState<SystemPick[]>([]),[tab,setTab]=useState<Tab>('Pronostici'),[filters,setFilters]=useState(initial),[detail,setDetail]=useState<Row|null>(null),[drawer,setDrawer]=useState(false),[mode,setMode]=useState<Mode>('PRESEASON'),[meta,setMeta]=useState<any>({});
 const load=()=>{setLoading(true);setError('');const endpoint=mode==='PRESEASON'?'/v2/preseason':'/v2/predictions';void request(`${API}${endpoint}?competition=SA&persist=true`).then(b=>{setRows(shortRows(b.data||[]));setMeta(b)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))};
 useEffect(load,[mode]);
 const addPick=(p:SystemPick)=>setBag(x=>x.some(i=>i.id===p.id)?x:[...x,p]);
 const add=(row:Row,m:Market)=>addPick(pick(row,m));
 const available=useMemo(()=>rows.flatMap(r=>featured(r).filter(m=>m.status==='ACTIVE').map(m=>pick(r,m))),[rows]);
 const navigate=(t:Tab)=>{setTab(t);setDrawer(false)};
 if(detail)return <MobileDetail row={detail} bag={bag} addPick={addPick} back={()=>setDetail(null)}/>;
 return <div className="mShell"><header className="mHead"><button className="mMenu" aria-label="Apri menu" onClick={()=>setDrawer(true)}>☰</button><div className="mHeadTitle"><small>FORESIGHT · SERIE A</small><h1>{tab}</h1></div><div className="mHeadStatus"><span className={mode==='LIVE'?'mLive':'mTest'}>{mode==='LIVE'?'● LIVE':'◐ TEST'}</span><small>{RELEASE}</small></div></header>
 {drawer&&<Drawer tab={tab} mode={mode} setMode={m=>{setMode(m);setDrawer(false);setTab('Pronostici')}} navigate={navigate} close={()=>setDrawer(false)}/>}<main className="mMain">
  {tab==='Pronostici'&&<Pred rows={rows} loading={loading} error={error} retry={load} bag={bag} filters={filters} setFilters={setFilters} add={add} open={setDetail} mode={mode} meta={meta}/>} 
  {tab==='Partite'&&<Fixtures rows={rows} open={setDetail}/>} 
  {tab==='Sistema'&&<SystemBuilderPanel bag={bag} setBag={setBag} available={available}/>} 
  {tab==='Storico'&&<HistoryDashboard/>} 
  {tab==='Statistiche'&&<StatsDashboard/>}
  {tab==='I miei sistemi'&&<SavedSystems/>}
  {tab==='Impostazioni'&&<Settings mode={mode}/>} 
 </main>{bag.length>0&&tab!=='Sistema'&&<button className="mSlip" aria-label={`Apri sistema con ${bag.length} selezioni`} onClick={()=>setTab('Sistema')}><span><b>{bag.length}</b> selezioni</span><strong>Apri sistema →</strong></button>}
 <nav className="mNav mNav4" aria-label="Navigazione principale">{([['Pronostici','◉'],['Partite','⚽'],['Sistema','＋'],['Storico','◷']]as[Tab,string][]).map(([t,i])=><button key={t} aria-current={tab===t?'page':undefined} className={tab===t?'on':''} onClick={()=>setTab(t)}><span aria-hidden="true">{i}</span><small>{t}</small></button>)}</nav></div>
}

function Drawer({tab,mode,setMode,navigate,close}:{tab:Tab;mode:Mode;setMode:(m:Mode)=>void;navigate:(t:Tab)=>void;close:()=>void}){return <div className="mDrawerLayer" role="dialog" aria-modal="true" aria-label="Menu principale" onClick={close}><aside className="mDrawer" onClick={e=>e.stopPropagation()}><div className="mDrawerHead"><div><small>FPS FORESIGHT</small><b>{RELEASE}</b></div><button aria-label="Chiudi menu" onClick={close}>×</button></div><section><small>MODALITÀ DATI</small><div className="mModeSwitch"><button className={mode==='PRESEASON'?'on':''} onClick={()=>setMode('PRESEASON')}>◐ Preseason/Test</button><button className={mode==='LIVE'?'on':''} onClick={()=>setMode('LIVE')}>● Live</button></div></section><nav>{(['Pronostici','Partite','Sistema','I miei sistemi','Storico','Statistiche','Impostazioni']as Tab[]).map(t=><button key={t} className={tab===t?'on':''} onClick={()=>navigate(t)}>{t}<span>›</span></button>)}</nav><footer><small>Serie A · probabilità, non certezze</small><small>Backtest e snapshot restano versionati.</small></footer></aside></div>}

function MobileDetail({row,bag,addPick,back}:{row:Row;bag:SystemPick[];addPick:(p:SystemPick)=>void;back:()=>void}){return <div className="mShell"><header className="mHead"><button className="mBack" aria-label="Torna ai pronostici" onClick={back}>←</button><div><small>DETTAGLIO PARTITA</small><h1>{row.fixture.home.name} — {row.fixture.away.name}</h1></div></header><main className="mMain"><section className="mIntro"><small>{day(row.fixture.utcDate)}</small><h2>{row.fixture.home.name} — {row.fixture.away.name}</h2><p>xG modello: {row.expectedGoalsHome==null?'—':Number(row.expectedGoalsHome).toFixed(2)} — {row.expectedGoalsAway==null?'—':Number(row.expectedGoalsAway).toFixed(2)}</p></section><MatchIntelligence fixtureId={row.fixture.id}/><DetailPanels row={row} selected={id=>bag.some(p=>p.id===id)} add={addPick}/></main><nav className="mNav" aria-label="Navigazione dettaglio"><button onClick={back}><span>←</span><small>Indietro</small></button><button className="on" aria-current="page"><span>⚽</span><small>Partita</small></button></nav></div>}

function Pred({rows,loading,error,retry,bag,filters,setFilters,add,open,mode,meta}:{rows:Row[];loading:boolean;error:string;retry:()=>void;bag:SystemPick[];filters:FilterState;setFilters:(f:FilterState)=>void;add:(r:Row,m:Market)=>void;open:(r:Row)=>void;mode:Mode;meta:any}){const filtered=useMemo(()=>apply(rows,filters),[rows,filters]),groups=useMemo(()=>group(filtered),[filtered]),highlights=useMemo(()=>dailyHighlights(rows),[rows]);if(loading)return <div className="mLoading" role="status">Analisi delle partite…</div>;
 const season=meta?.historicalSeason?`${meta.historicalSeason}/${String(meta.historicalSeason+1).slice(-2)}`:'';
 return <>{error&&<div className="mNotice" role="alert"><b>Dati non disponibili</b><span>{error}. Nessun valore viene sostituito con dati inventati.</span><button onClick={retry}>Riprova</button></div>}{mode==='PRESEASON'&&<div className="mModeNotice"><b>Modalità Preseason/Test</b><span>{season?`Prior storico Serie A ${season}. `:''}I dati della nuova stagione acquistano peso progressivamente. Confidence e Data Quality sono penalizzate rispetto al Live.</span></div>}<FilterBar value={filters} onChange={setFilters}/><Highlights items={highlights} bag={bag} add={add} open={open}/><section className="mIntro"><div><small>SERIE A · MODELLO VERSIONATO</small><h2>Probabilità, non certezze.</h2><p>Apri una partita solo quando vuoi vedere i mercati. Probability, Confidence e Data Quality restano indicatori distinti.</p></div></section>{!filtered.length?<div className="mEmpty">Nessun evento corrisponde ai filtri.</div>:groups.map(([d,rs])=><section className="mDay" key={d}><div className="mDayHead"><h2>{d}</h2><span>{rs.length} eventi</span></div>{rs.map(r=><MatchCard key={r.fixture.id} row={r} quick={filters.quick} selected={m=>bag.some(p=>p.id===pid(r,m))} onAdd={m=>add(r,m)} onOpen={()=>open(r)}/>)}</section>)}</>}

function Highlights({items,bag,add,open}:{items:Highlight[];bag:SystemPick[];add:(r:Row,m:Market)=>void;open:(r:Row)=>void}){if(!items.length)return <section className="mHighlights"><div className="mSectionHead"><div><small>IN EVIDENZA OGGI</small><h2>Nessun pick supera i gate</h2></div></div></section>;return <section className="mHighlights"><div className="mSectionHead"><div><small>IN EVIDENZA OGGI</small><h2>{items.length} selezion{items.length===1?'e':'i'} dal motore</h2></div><span>max 4</span></div><div className="mHighlightRail">{items.map(x=><article className={`mHighlight mHighlight-${x.tone}`} key={`${x.kind}-${pid(x.row,x.market)}`}><small>{x.icon} {x.kind}</small><button className="mHighlightMatch" onClick={()=>open(x.row)}>{x.row.fixture.home.name} — {x.row.fixture.away.name}</button><h3>{marketLabel(x.row,x.market)}</h3><div className="mHighlightMetrics"><span><b>{pct(x.market.probability)}</b>Prob.</span><span><b>{pct(x.market.confidence)}</b>Conf.</span><span><b>{pct(x.market.dataQuality)}</b>DQ</span></div><button disabled={bag.some(p=>p.id===pid(x.row,x.market))} onClick={()=>add(x.row,x.market)}>{bag.some(p=>p.id===pid(x.row,x.market))?'Nel sistema':'＋ Sistema'}</button></article>)}</div></section>}

function Fixtures({rows,open}:{rows:Row[];open:(r:Row)=>void}){const[q,setQ]=useState('');const f=rows.filter(r=>`${r.fixture.home.name} ${r.fixture.away.name}`.toLowerCase().includes(q.toLowerCase()));return <section className="mPanel"><label className="mSearch">Squadra<input aria-label="Filtra partite per squadra" value={q} onChange={e=>setQ(e.target.value)} placeholder="es. Napoli"/></label>{f.length?f.map(r=><button className="mFixture" key={r.fixture.id} onClick={()=>open(r)}><span><small>{day(r.fixture.utcDate)}</small><b>{r.fixture.home.name} — {r.fixture.away.name}</b></span><strong>→</strong></button>):<div className="mEmpty">Nessuna partita corrisponde al filtro.</div>}</section>}

function SavedSystems(){const[items,setItems]=useState<any[]>([]),[mode,setMode]=useState(''),[error,setError]=useState('');useEffect(()=>{setError('');void request(`${API}/v2/history/systems${mode?`?mode=${mode}`:''}`).then(x=>setItems(Array.isArray(x)?x:[])).catch(e=>{setItems([]);setError(e.message)})},[mode]);return <section className="mPanel"><div className="mSectionHead"><div><small>PORTAFOGLIO</small><h2>I miei sistemi</h2></div><select aria-label="Filtra sistemi" value={mode} onChange={e=>setMode(e.target.value)}><option value="">Tutti</option><option value="PLAYED">Reali</option><option value="SIMULATED">Paper</option><option value="NOT_PLAYED">Non giocati</option></select></div>{error&&<div className="mNotice">{error}</div>}{items.length?items.map(s=><article className="mSaved" key={s.id}><span><b>{s.mode} · {s.selections?.length||0} selezioni</b><small>{s.combinations?.length||0} combinazioni · €{Number(s.totalCost||0).toFixed(2)} · {s.played?'REALE':s.simulated?'PAPER':'NON GIOCATO'}</small></span><strong>{s.status}</strong></article>):!error&&<div className="mEmpty">Nessun sistema salvato.</div>}</section>}

function Settings({mode}:{mode:Mode}){return <section className="mPanel"><small>APP</small><h2>Impostazioni</h2><p>Le credenziali provider sono conservate nel secure storage del dispositivo e non sono incluse nell’APK.</p><div className="mInfoRow"><span>Release</span><b>{RELEASE}</b></div><div className="mInfoRow"><span>Modalità</span><b>{mode==='PRESEASON'?'Preseason/Test':'Live'}</b></div><div className="mInfoRow"><span>Dati mancanti</span><b>NO_BET / UNAVAILABLE</b></div><div className="mInfoRow"><span>Settlement</span><b>Automatico e idempotente</b></div></section>}

type Highlight={kind:string;icon:string;tone:'safe'|'alt'|'surprise'|'try';row:Row;market:Market;score:number};
function dailyHighlights(rows:Row[]):Highlight[]{const now=Date.now(),all=rows.filter(r=>new Date(r.fixture.utcDate).getTime()>=now-1800000).flatMap(row=>row.markets.filter(m=>m.status==='ACTIVE').map(m=>({row,market:m,score:reliability(m)}))).filter(x=>x.market.confidence>=.50&&x.market.dataQuality>=.50),used=new Set<string>(),usedFixtures=new Set<string>(),out:Highlight[]=[];const take=(kind:string,icon:string,tone:Highlight['tone'],xs:typeof all,distinctFixture=false)=>{const x=[...xs].sort((a,b)=>b.score-a.score).find(v=>!used.has(pid(v.row,v.market))&&(!distinctFixture||!usedFixtures.has(v.row.fixture.id)));if(!x)return;used.add(pid(x.row,x.market));usedFixtures.add(x.row.fixture.id);out.push({kind,icon,tone,...x})};
 const robust=all.filter(x=>x.market.probability>=.55&&x.market.confidence>=.55);take('Pick del giorno','🛡️','safe',robust);const first=out[0]?.score??0;take('Alternativa','◆','alt',robust.filter(x=>x.score>=Math.max(.55,first-.08)),true);take('Sorpresa','⚡','surprise',all.filter(x=>x.market.probability>=.20&&x.market.probability<=.55&&x.market.confidence>=.55&&Number(x.market.fairOdds||0)>=1.8),true);take('Tentativo','🎯','try',all.filter(x=>(x.market.market==='EXACT_SCORE'||x.market.market.includes('SCORER'))&&x.market.probability>=.05&&x.market.probability<=.30));return out.slice(0,4)}
function reliability(m:Market){return m.probability*.45+m.confidence*.30+m.dataQuality*.25}
function marketLabel(r:Row,m:Market){if(m.market==='1X2')return m.selection==='1'?r.fixture.home.name:m.selection==='2'?r.fixture.away.name:'Pareggio';if(m.market==='EXACT_SCORE')return`Risultato esatto ${m.selection}`;if(m.market.includes('SCORER'))return`${m.selection} marcatore`;return String(m.selection).replaceAll('_',' ')}
function shortRows(rows:Row[]):Row[]{return rows.map(r=>({...r,fixture:{...r.fixture,home:{...r.fixture.home,name:shortTeam(r.fixture.home.name)},away:{...r.fixture.away,name:shortTeam(r.fixture.away.name)}}}))}
function shortTeam(name:string){const n=name.trim(),aliases:Record<string,string>={'FC Internazionale Milano':'Inter','Internazionale':'Inter','AC Milan':'Milan','SSC Napoli':'Napoli','AS Roma':'Roma','SS Lazio':'Lazio','ACF Fiorentina':'Fiorentina','Atalanta BC':'Atalanta','Bologna FC 1909':'Bologna','Cagliari Calcio':'Cagliari','Como 1907':'Como','Genoa CFC':'Genoa','Juventus FC':'Juventus','US Lecce':'Lecce','Parma Calcio 1913':'Parma','Torino FC':'Torino','Udinese Calcio':'Udinese','Hellas Verona FC':'Verona','US Sassuolo Calcio':'Sassuolo','US Cremonese':'Cremonese','Pisa SC':'Pisa'};if(aliases[n])return aliases[n];return n.replace(/\b(FC|AC|SSC|SS|AS|BC|CFC|US|Calcio|1907|1909|1913)\b/gi,'').replace(/\s+/g,' ').trim()||n}
function pid(r:Row,m:Market){return`${r.fixture.id}|${m.market}|${m.selection}`}
function pick(r:Row,m:Market):SystemPick{return{id:pid(r,m),fixtureId:r.fixture.id,market:m.market,selection:m.selection,eventAt:r.fixture.utcDate,probability:m.probability,confidence:m.confidence,dataQuality:m.dataQuality,fairOdds:m.fairOdds,period:m.period,metric:m.metric,operator:m.operator,threshold:m.threshold,outcome:m.outcome}}
function apply(rows:Row[],f:FilterState){const now=new Date();const until=f.scope==='TODAY'?edge(now,0):f.scope==='3D'?edge(now,3):f.scope==='7D'?edge(now,7):null;const out=rows.filter(r=>{if(f.team&&!`${r.fixture.home.name} ${r.fixture.away.name}`.toLowerCase().includes(f.team.toLowerCase()))return false;const t=new Date(r.fixture.utcDate);if(until&&(t<start(now)||t>until))return false;if(f.quick==='NO BET')return r.markets.some(m=>m.status==='NO_BET');return forQuick(r,f.quick).filter(m=>m.status==='ACTIVE').some(m=>m.probability*100>=f.minP&&m.confidence*100>=f.minC&&m.dataQuality*100>=f.minD)});return out.sort((a,b)=>f.sort==='TIME'?+new Date(a.fixture.utcDate)-+new Date(b.fixture.utcDate):metric(b,f)-metric(a,f))}
function metric(r:Row,f:FilterState){const m=forQuick(r,f.quick).filter(x=>x.status==='ACTIVE').sort((a,b)=>b.probability-a.probability)[0];return f.sort==='PROBABILITY'?m?.probability||0:f.sort==='CONFIDENCE'?m?.confidence||0:m?.dataQuality||0}
function group(rows:Row[]){const m=new Map<string,Row[]>();rows.forEach(r=>{const k=day(r.fixture.utcDate);m.set(k,[...(m.get(k)||[]),r])});return[...m.entries()]}
function start(d:Date){const x=new Date(d);x.setHours(0,0,0,0);return x}function edge(d:Date,n:number){const x=new Date(d);x.setDate(x.getDate()+n);x.setHours(23,59,59,999);return x}
