import React,{useEffect,useMemo,useState}from'react';
import HistoryDashboard from'../../web/app/HistoryDashboard';
import StatsDashboard from'../../web/app/StatsDashboard';
import SystemBuilderPanel,{type SystemPick}from'../../web/app/SystemBuilderPanel';
import MatchIntelligence from'../../web/app/MatchIntelligence';
import{FilterBar,type FilterState}from'./FilterBar';
import{MatchCard,MarketLine}from'./MatchCard';
import type{Market,Row}from'./mobile-types';
import{day,featured,forQuick,pct}from'./mobile-types';
const API='http://localhost:4000',RELEASE='v1.2.0-beta.1';
type Mode='PRESEASON'|'LIVE';type Tab='Home'|'Partite'|'Sistema'|'Storico'|'Statistiche'|'I miei sistemi'|'Impostazioni';
const initial:FilterState={quick:'Tutti',team:'',scope:'ALL',minP:0,minC:0,minD:0,sort:'TIME'};
async function request(url:string){const r=await fetch(url),b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.message||`${r.status}`);return b}
export default function MobileHomeV3(){const[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[bag,setBag]=useState<SystemPick[]>([]),[tab,setTab]=useState<Tab>('Home'),[filters,setFilters]=useState(initial),[detail,setDetail]=useState<Row|null>(null),[drawer,setDrawer]=useState(false),[mode,setMode]=useState<Mode>('PRESEASON'),[meta,setMeta]=useState<any>({}),[toast,setToast]=useState('');
 const load=()=>{setLoading(true);setError('');const endpoint=mode==='PRESEASON'?'/v2/preseason':'/v2/predictions';void request(`${API}${endpoint}?competition=SA&persist=true`).then(b=>{setRows(shortRows(b.data||[]));setMeta(b)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))};useEffect(load,[mode]);
 const toggle=(row:Row,m:Market)=>{const p=pick(row,m),exists=bag.some(x=>x.id===p.id);setBag(x=>exists?x.filter(i=>i.id!==p.id):[...x,p]);setToast(exists?'Pronostico rimosso dal sistema':'Pronostico aggiunto al sistema');window.setTimeout(()=>setToast(''),1800)};
 const available=useMemo(()=>rows.flatMap(r=>featured(r).filter(m=>m.status==='ACTIVE').map(m=>pick(r,m))),[rows]);
 if(detail)return <Detail row={detail} bag={bag} toggle={toggle} back={()=>setDetail(null)}/>;
 return <div className="mShell v3Shell"><header className="v3Header"><button className="v3Icon" aria-label="Apri menu" onClick={()=>setDrawer(true)}>☰</button><div><small>FPS FORESIGHT · SERIE A</small><h1>{tab==='Home'?'Pronostici':tab}</h1></div><span className="v3Release">{RELEASE}</span></header>{drawer&&<Drawer tab={tab} mode={mode} navigate={t=>{setTab(t);setDrawer(false)}} setMode={m=>{setMode(m);setDrawer(false);setTab('Home')}} close={()=>setDrawer(false)}/>}<main className="mMain v3Main">{tab==='Home'&&<Home rows={rows} loading={loading} error={error} retry={load} bag={bag} filters={filters} setFilters={setFilters} toggle={toggle} open={setDetail} mode={mode} meta={meta}/>} {tab==='Partite'&&<Fixtures rows={rows} open={setDetail}/>} {tab==='Sistema'&&<SystemIntro bag={bag}><SystemBuilderPanel bag={bag} setBag={setBag} available={available}/></SystemIntro>} {tab==='Storico'&&<HistoryDashboard/>}{tab==='Statistiche'&&<StatsDashboard/>}{tab==='I miei sistemi'&&<SavedSystems/>}{tab==='Impostazioni'&&<Settings mode={mode}/>}</main>{toast&&<div className="v3Toast" role="status">{toast}</div>}{bag.length>0&&tab!=='Sistema'&&<button className="v3Slip" onClick={()=>setTab('Sistema')}><span><b>{bag.length}</b> {bag.length===1?'pronostico selezionato':'pronostici selezionati'}</span><strong>Apri sistema ›</strong></button>}<nav className="v3Bottom" aria-label="Navigazione principale">{([['Home','⌂'],['Partite','⚽'],['Sistema','＋'],['Storico','◷']]as[Tab,string][]).map(([t,i])=><button key={t} className={tab===t?'on':''} aria-current={tab===t?'page':undefined} onClick={()=>setTab(t)}><span>{i}</span><small>{t}</small>{t==='Sistema'&&bag.length>0&&<i>{bag.length}</i>}</button>)}</nav></div>}
function Drawer({tab,mode,navigate,setMode,close}:{tab:Tab;mode:Mode;navigate:(t:Tab)=>void;setMode:(m:Mode)=>void;close:()=>void}){return <div className="mDrawerLayer" role="dialog" aria-modal="true" onClick={close}><aside className="mDrawer v3Drawer" onClick={e=>e.stopPropagation()}><div className="mDrawerHead"><div><small>FPS FORESIGHT</small><b>{RELEASE}</b></div><button aria-label="Chiudi menu" onClick={close}>×</button></div><div className="v3DataStatus"><span>{mode==='LIVE'?'● Dati stagione corrente':'◐ Stime con storico precedente'}</span><small>{mode==='LIVE'?'Usa i dati disponibili della stagione in corso.':'Il campionato non è ancora maturo: usiamo anche la stagione precedente e riduciamo l’affidabilità.'}</small></div><nav>{(['Home','Partite','Sistema','I miei sistemi','Storico','Statistiche','Impostazioni']as Tab[]).map(t=><button key={t} className={tab===t?'on':''} onClick={()=>navigate(t)}>{labelTab(t)}<span>›</span></button>)}</nav><details className="v3Expert"><summary>Opzioni dati avanzate</summary><div><button className={mode==='PRESEASON'?'on':''} onClick={()=>setMode('PRESEASON')}>Usa anche stagione precedente</button><button className={mode==='LIVE'?'on':''} onClick={()=>setMode('LIVE')}>Solo stagione corrente</button></div></details><footer><small>Le percentuali sono stime, non certezze.</small></footer></aside></div>}
function Home({rows,loading,error,retry,bag,filters,setFilters,toggle,open,mode,meta}:{rows:Row[];loading:boolean;error:string;retry:()=>void;bag:SystemPick[];filters:FilterState;setFilters:(f:FilterState)=>void;toggle:(r:Row,m:Market)=>void;open:(r:Row)=>void;mode:Mode;meta:any}){const filtered=useMemo(()=>apply(rows,filters),[rows,filters]),groups=useMemo(()=>group(filtered),[filtered]),highlights=useMemo(()=>dailyHighlights(rows),[rows]);if(loading)return <div className="v3Loading"><span></span><b>Sto analizzando le prossime partite…</b><small>Controllo dati, forma e mercati disponibili.</small></div>;const season=meta?.historicalSeason?`${meta.historicalSeason}/${String(meta.historicalSeason+1).slice(-2)}`:'';return <>{error&&<div className="v3Message error"><b>Non riesco ad aggiornare i dati</b><span>{error}</span><small>Non verranno mostrati valori inventati.</small><button onClick={retry}>Riprova</button></div>}{mode==='PRESEASON'&&<div className="v3Message info"><b>ℹ Stime di inizio stagione</b><span>{season?`Usiamo anche i dati Serie A ${season}. `:''}Quando arriveranno nuove partite, i dati attuali avranno sempre più peso.</span><details><summary>Cosa significa?</summary><p>L’affidabilità viene ridotta perché una parte dell’analisi usa informazioni della stagione precedente.</p></details></div>}<section className="v3Welcome"><small>OGGI</small><h2>Da dove vuoi iniziare?</h2><p>Guarda i pronostici più interessanti oppure scegli una partita. Tocca un pronostico per aggiungerlo al tuo sistema; toccalo di nuovo per rimuoverlo.</p></section><Highlights items={highlights} bag={bag} toggle={toggle} open={open}/><FilterBar value={filters} onChange={setFilters}/>{!filtered.length?<div className="v3Empty"><b>Nessuna partita trovata</b><span>Prova a cambiare i filtri.</span></div>:groups.map(([d,rs],index)=><section className="v3Round" key={d}><div className="v3RoundHead"><div><small>{index===0?'PROSSIME PARTITE':'A SEGUIRE'}</small><h2>{d}</h2></div><span>{rs.length} {rs.length===1?'partita':'partite'}</span></div>{rs.map(r=><MatchCard key={r.fixture.id} row={r} quick={filters.quick} selected={m=>bag.some(p=>p.id===pid(r,m))} onAdd={m=>toggle(r,m)} onOpen={()=>open(r)}/>)}</section>)}</>}
function Highlights({items,bag,toggle,open}:{items:Highlight[];bag:SystemPick[];toggle:(r:Row,m:Market)=>void;open:(r:Row)=>void}){return <section className="v3Highlights"><div className="v3SectionTitle"><div><small>IN EVIDENZA</small><h2>Le scelte da guardare</h2></div><span>fino a 4</span></div>{!items.length?<div className="v3Empty"><b>Nessuna scelta abbastanza solida</b><span>È un risultato valido: non forziamo un pronostico.</span></div>:<div className="v3HighlightGrid">{items.map(x=>{const sel=bag.some(p=>p.id===pid(x.row,x.market));return <article className={`v3Highlight ${x.tone}`} key={`${x.kind}-${pid(x.row,x.market)}`}><button className="v3HighlightBody" onClick={()=>open(x.row)}><small>{x.icon} {friendlyKind(x.kind)}</small><span>{x.row.fixture.home.name} vs {x.row.fixture.away.name}</span><h3>{marketLabel(x.row,x.market)}</h3><div><b>{pct(x.market.probability)}</b><small>probabilità</small></div><em>Affidabilità {trust(x.market.confidence)}</em></button><button className={sel?'selected':''} aria-pressed={sel} onClick={()=>toggle(x.row,x.market)}>{sel?'✓ Selezionato · rimuovi':'+ Aggiungi al sistema'}</button></article>})}</div>}</section>}
function Detail({row,bag,toggle,back}:{row:Row;bag:SystemPick[];toggle:(r:Row,m:Market)=>void;back:()=>void}){const[c,setC]=useState('Esito');const active=row.markets.filter(m=>m.status==='ACTIVE'),top=[...active].sort((a,b)=>reliability(b)-reliability(a))[0],cats=['Esito','Gol','Gol squadra','Risultati'];const shown=row.markets.filter(m=>cat(m)===c);return <div className="mShell v3Shell"><header className="v3Header"><button className="v3Icon" onClick={back} aria-label="Torna alle partite">←</button><div><small>PARTITA</small><h1>{row.fixture.home.name} vs {row.fixture.away.name}</h1></div></header><main className="mMain v3Main"><section className="v3DetailHero"><small>{day(row.fixture.utcDate)}</small><h2>{row.fixture.home.name} <span>vs</span> {row.fixture.away.name}</h2>{top?<div className="v3PrimaryAdvice"><small>IL NOSTRO PRONOSTICO PRINCIPALE</small><h3>{marketLabel(row,top)}</h3><div><b>{pct(top.probability)}</b><span>Probabilità stimata</span></div><em>Affidabilità {trust(top.confidence)}</em><button className={bag.some(p=>p.id===pid(row,top))?'selected':''} onClick={()=>toggle(row,top)}>{bag.some(p=>p.id===pid(row,top))?'✓ Selezionato · tocca per rimuovere':'+ Aggiungi al sistema'}</button></div>:<div className="v3NoAdvice"><b>Nessun pronostico consigliato</b><span>I dati non superano i controlli minimi di qualità.</span></div>}</section><section className="v3Markets"><div className="v3SectionTitle"><div><small>ALTRI PRONOSTICI</small><h2>Scegli cosa vuoi vedere</h2></div></div><div className="v3MarketTabs">{cats.map(x=><button className={c===x?'on':''} onClick={()=>setC(x)} key={x}>{x}</button>)}</div>{shown.length?shown.map(m=><MarketLine key={`${m.market}-${m.selection}`} market={m} selected={bag.some(p=>p.id===pid(row,m))} add={()=>toggle(row,m)}/>):<div className="v3Empty">Nessun pronostico disponibile in questa categoria.</div>}</section><details className="v3AdvancedAnalysis"><summary>Analisi e dati avanzati</summary><p>Questa sezione è facoltativa. Serve se vuoi approfondire perché il modello ha prodotto queste stime.</p><MatchIntelligence fixtureId={row.fixture.id}/></details></main>{bag.length>0&&<button className="v3Slip" onClick={back}><span><b>{bag.length}</b> nel sistema</span><strong>Continua ›</strong></button>}</div>}
function Fixtures({rows,open}:{rows:Row[];open:(r:Row)=>void}){const[q,setQ]=useState(''),groups=group(rows.filter(r=>`${r.fixture.home.name} ${r.fixture.away.name}`.toLowerCase().includes(q.toLowerCase())));return <><section className="v3Welcome"><small>CALENDARIO</small><h2>Partite di Serie A</h2><p>Scegli una partita per vedere tutti i pronostici disponibili.</p></section><label className="v3Search">Cerca una squadra<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Es. Como"/></label>{groups.map(([d,rs])=><section className="v3Round" key={d}><div className="v3RoundHead"><h2>{d}</h2><span>{rs.length} partite</span></div>{rs.map(r=><button className="v3Fixture" key={r.fixture.id} onClick={()=>open(r)}><span><small>{new Date(r.fixture.utcDate).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}</small><b>{r.fixture.home.name} <i>vs</i> {r.fixture.away.name}</b></span><strong>›</strong></button>)}</section>)}</>}
function SystemIntro({bag,children}:{bag:SystemPick[];children:React.ReactNode}){return <><section className="v3Welcome"><small>IL TUO SISTEMA</small><h2>{bag.length?`${bag.length} ${bag.length===1?'pronostico scelto':'pronostici scelti'}`:'Costruiamo il tuo sistema'}</h2><p>{bag.length?'Puoi rimuovere una scelta tornando alla partita e toccando di nuovo “Selezionato”.':'Scegli i pronostici dalle partite oppure lascia che FPS ti aiuti a costruire una proposta.'}</p></section>{children}</>}
function SavedSystems(){const[items,setItems]=useState<any[]>([]);useEffect(()=>{void request(`${API}/v2/history/systems`).then(x=>setItems(Array.isArray(x)?x:[])).catch(()=>setItems([]))},[]);return <section className="mPanel"><div className="v3Welcome"><small>SALVATI</small><h2>I miei sistemi</h2><p>Qui trovi i sistemi che hai creato, simulato o realmente giocato.</p></div>{items.length?items.map(s=><article className="mSaved" key={s.id}><span><b>{s.selections?.length||0} selezioni</b><small>{s.played?'Giocato realmente':s.simulated?'Simulazione':'Non giocato'} · €{Number(s.totalCost||0).toFixed(2)}</small></span><strong>{s.status}</strong></article>):<div className="v3Empty">Non hai ancora salvato sistemi.</div>}</section>}
function Settings({mode}:{mode:Mode}){return <section className="mPanel"><div className="v3Welcome"><small>APP</small><h2>Impostazioni</h2><p>Le opzioni tecniche sono raccolte qui per mantenere semplice l’uso quotidiano.</p></div><div className="mInfoRow"><span>Versione</span><b>{RELEASE}</b></div><div className="mInfoRow"><span>Fonte dati</span><b>{mode==='PRESEASON'?'Anche stagione precedente':'Stagione corrente'}</b></div><div className="mInfoRow"><span>Dati insufficienti</span><b>Nessun consiglio</b></div></section>}
type Highlight={kind:string;icon:string;tone:'safe'|'alt'|'surprise'|'try';row:Row;market:Market;score:number};
function dailyHighlights(rows:Row[]):Highlight[]{const all=rows.flatMap(row=>row.markets.filter(m=>m.status==='ACTIVE').map(m=>({row,market:m,score:reliability(m)}))).filter(x=>x.market.confidence>=.5&&x.market.dataQuality>=.5),used=new Set<string>(),fixtures=new Set<string>(),out:Highlight[]=[];const take=(kind:string,icon:string,tone:Highlight['tone'],xs:typeof all)=>{const x=[...xs].sort((a,b)=>b.score-a.score).find(v=>!used.has(pid(v.row,v.market))&&!fixtures.has(v.row.fixture.id));if(x){used.add(pid(x.row,x.market));fixtures.add(x.row.fixture.id);out.push({kind,icon,tone,...x})}};take('Pick del giorno','🛡️','safe',all.filter(x=>x.market.probability>=.55&&x.market.confidence>=.55));take('Alternativa','◆','alt',all.filter(x=>x.market.probability>=.5));take('Sorpresa','⚡','surprise',all.filter(x=>x.market.probability>=.2&&x.market.probability<=.55&&x.market.confidence>=.55));take('Tentativo','🎯','try',all.filter(x=>(x.market.market==='EXACT_SCORE'||x.market.market.includes('SCORER'))&&x.market.probability>=.05&&x.market.probability<=.3));return out.slice(0,4)}
function trust(v:number){return v>=.75?'alta':v>=.58?'media':'bassa'}function friendlyKind(k:string){return k==='Pick del giorno'?'Più affidabile':k}
function marketLabel(r:Row,m:Market){if(m.market==='1X2')return m.selection==='1'?`${r.fixture.home.name} vincente`:m.selection==='2'?`${r.fixture.away.name} vincente`:'Pareggio';if(m.market==='EXACT_SCORE')return`Risultato esatto ${m.selection}`;if(m.market.includes('SCORER'))return`${m.selection} marcatore`;if(m.market==='BTTS')return m.selection==='YES'?'Entrambe segnano':'Almeno una non segna';return String(m.selection).replaceAll('_',' ')}
function cat(m:Market){if(m.market==='1X2'||m.market.includes('DOUBLE'))return'Esito';if(m.market==='EXACT_SCORE')return'Risultati';if(m.market.includes('TEAM'))return'Gol squadra';return'Gol'}function reliability(m:Market){return m.probability*.45+m.confidence*.3+m.dataQuality*.25}function pid(r:Row,m:Market){return`${r.fixture.id}|${m.market}|${m.selection}`}
function pick(r:Row,m:Market):SystemPick{return{id:pid(r,m),fixtureId:r.fixture.id,market:m.market,selection:m.selection,eventAt:r.fixture.utcDate,probability:m.probability,confidence:m.confidence,dataQuality:m.dataQuality,fairOdds:m.fairOdds,period:m.period,metric:m.metric,operator:m.operator,threshold:m.threshold,outcome:m.outcome}}
function shortRows(rows:Row[]):Row[]{return rows.map(r=>({...r,fixture:{...r.fixture,home:{...r.fixture.home,name:shortTeam(r.fixture.home.name)},away:{...r.fixture.away,name:shortTeam(r.fixture.away.name)}}}))}function shortTeam(name:string){const aliases:Record<string,string>={'FC Internazionale Milano':'Inter','AC Milan':'Milan','SSC Napoli':'Napoli','AS Roma':'Roma','SS Lazio':'Lazio','ACF Fiorentina':'Fiorentina','Atalanta BC':'Atalanta','Bologna FC 1909':'Bologna','Cagliari Calcio':'Cagliari','Como 1907':'Como','Genoa CFC':'Genoa','Juventus FC':'Juventus','US Lecce':'Lecce','Parma Calcio 1913':'Parma','Torino FC':'Torino','Udinese Calcio':'Udinese','Hellas Verona FC':'Verona','US Sassuolo Calcio':'Sassuolo','US Cremonese':'Cremonese','Pisa SC':'Pisa'};return aliases[name.trim()]||name.replace(/\b(FC|AC|SSC|SS|AS|BC|CFC|US|Calcio|1907|1909|1913)\b/gi,'').replace(/\s+/g,' ').trim()}
function apply(rows:Row[],f:FilterState){return rows.filter(r=>{if(f.team&&!`${r.fixture.home.name} ${r.fixture.away.name}`.toLowerCase().includes(f.team.toLowerCase()))return false;const ms=f.quick==='NO BET'?r.markets:forQuick(r,f.quick);if(f.quick==='NO BET')return ms.some(m=>m.status==='NO_BET');return ms.some(m=>m.status==='ACTIVE'&&m.probability*100>=f.minP&&m.confidence*100>=f.minC&&m.dataQuality*100>=f.minD)}).sort((a,b)=>+new Date(a.fixture.utcDate)-+new Date(b.fixture.utcDate))}function group(rows:Row[]){const m=new Map<string,Row[]>();rows.forEach(r=>{const k=day(r.fixture.utcDate);m.set(k,[...(m.get(k)||[]),r])});return[...m.entries()]}function labelTab(t:Tab){return t==='Home'?'Pronostici':t}
