import React,{useEffect,useMemo,useState}from'react';
import HistoryDashboard from'../../web/app/HistoryDashboard';
import StatsDashboard from'../../web/app/StatsDashboard';
import SystemBuilderPanel,{type SystemPick}from'../../web/app/SystemBuilderPanel';
import MatchIntelligence from'../../web/app/MatchIntelligence';
import DataFreshnessBar from'./DataFreshnessBar';
import type{Market,Row}from'./mobile-types';
import{day,featured,pct}from'./mobile-types';

const API='http://localhost:4000',RELEASE='v1.2.0-beta.4';
type Tab='Home'|'Partite'|'Sistema'|'Storico'|'Statistiche'|'I miei sistemi'|'Impostazioni';
type Mode='PRESEASON'|'LIVE';
type SimpleFilter='Tutte'|'Più affidabili'|'Gol'|'Over/Under'|'Marcatori';

async function request(url:string){const r=await fetch(url),b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.message||`${r.status}`);return b}

export default function MobileHomeV4(){
 const[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[bag,setBag]=useState<SystemPick[]>([]),[tab,setTab]=useState<Tab>('Home'),[detail,setDetail]=useState<Row|null>(null),[drawer,setDrawer]=useState(false),[mode,setMode]=useState<Mode>('PRESEASON'),[toast,setToast]=useState('');
 const load=()=>{setLoading(true);setError('');const endpoint=mode==='PRESEASON'?'/v2/preseason':'/v2/predictions';void request(`${API}${endpoint}?competition=SA&persist=true`).then(b=>setRows(shortRows(b.data||[]))).catch(e=>setError(e.message)).finally(()=>setLoading(false))};
 useEffect(load,[mode]);
 const toggle=(row:Row,m:Market)=>{const p=pick(row,m),exists=bag.some(x=>x.id===p.id);setBag(x=>exists?x.filter(i=>i.id!==p.id):[...x,p]);setToast(exists?'Rimosso dal sistema':'Aggiunto al sistema');window.setTimeout(()=>setToast(''),1400)};
 const available=useMemo(()=>rows.flatMap(r=>featured(r).filter(m=>m.status==='ACTIVE').map(m=>pick(r,m))),[rows]);
 if(detail)return <MatchDetail row={detail} bag={bag} toggle={toggle} back={()=>setDetail(null)} openSystem={()=>{setDetail(null);setTab('Sistema')}}/>;
 return <div className="mShell v4Shell"><header className="v4Header"><button className="v4Icon" aria-label="Apri menu" onClick={()=>setDrawer(true)}>☰</button><div><small>SERIE A</small><h1>{tab}</h1></div><span>{RELEASE}</span></header>
 <DataFreshnessBar onRefresh={load}/>
 {drawer&&<Drawer tab={tab} mode={mode} close={()=>setDrawer(false)} navigate={t=>{setTab(t);setDrawer(false)}} setMode={m=>{setMode(m);setTab('Home');setDrawer(false)}}/>}
 <main className="v4Main">{tab==='Home'&&<Home rows={rows} bag={bag} loading={loading} error={error} retry={load} toggle={toggle} open={setDetail}/>} {tab==='Partite'&&<Fixtures rows={rows} open={setDetail}/>} {tab==='Sistema'&&<SystemBuilderPanel bag={bag} setBag={setBag} available={available}/>} {tab==='Storico'&&<HistoryDashboard/>}{tab==='Statistiche'&&<StatsDashboard/>}{tab==='I miei sistemi'&&<SavedSystems/>}{tab==='Impostazioni'&&<Settings mode={mode}/>}</main>
 {toast&&<div className="v4Toast" role="status">{toast}</div>}
 {bag.length>0&&tab!=='Sistema'&&<button className="v4Slip" onClick={()=>setTab('Sistema')}><span><b>{bag.length}</b> {bag.length===1?'selezione':'selezioni'}</span><strong>Apri sistema ›</strong></button>}
 <nav className="v4Bottom" aria-label="Navigazione principale">{([['Home','⌂'],['Partite','⚽'],['Sistema','＋'],['Storico','◷']]as[Tab,string][]).map(([t,i])=><button key={t} className={tab===t?'on':''} aria-current={tab===t?'page':undefined} onClick={()=>setTab(t)}><span>{i}</span><small>{t}</small>{t==='Sistema'&&bag.length>0&&<i>{bag.length}</i>}</button>)}</nav></div>
}

function Home({rows,bag,loading,error,retry,toggle,open}:{rows:Row[];bag:SystemPick[];loading:boolean;error:string;retry:()=>void;toggle:(r:Row,m:Market)=>void;open:(r:Row)=>void}){
 const[filter,setFilter]=useState<SimpleFilter>('Tutte'),[team,setTeam]=useState('');
 const highlights=useMemo(()=>dailyHighlights(rows),[rows]);
 const filtered=useMemo(()=>rows.filter(r=>{if(team&&!`${r.fixture.home.name} ${r.fixture.away.name}`.toLowerCase().includes(team.toLowerCase()))return false;if(filter==='Più affidabili')return r.markets.some(m=>m.status==='ACTIVE'&&m.confidence>=.7);if(filter==='Gol')return r.markets.some(m=>m.status==='ACTIVE'&&['BTTS','MULTIGOAL','GOALS_PARITY'].includes(m.market));if(filter==='Over/Under')return r.markets.some(m=>m.status==='ACTIVE'&&m.market.startsWith('OVER_UNDER'));if(filter==='Marcatori')return r.markets.some(m=>m.status==='ACTIVE'&&m.market.includes('SCORER'));return true}),[rows,filter,team]);
 if(loading)return <div className="v4State"><b>Analisi delle partite…</b></div>;
 return <>{error&&<div className="v4Alert"><b>Dati non disponibili</b><span>{error}</span><button onClick={retry}>Riprova</button></div>}
 <section className="v4Highlights"><div className="v4SectionHead"><h2>In evidenza</h2><span>fino a 4</span></div>{highlights.length?<div className="v4HighlightRail">{highlights.map(x=>{const selected=bag.some(p=>p.id===pid(x.row,x.market));return <article className={`v4Highlight ${x.tone}`} key={`${x.kind}-${pid(x.row,x.market)}`}><button className="v4HighlightBody" onClick={()=>open(x.row)}><small>{x.icon} {friendlyKind(x.kind)}</small><span className="v4HighlightDate">{compactDate(x.row.fixture.utcDate)} · {new Date(x.row.fixture.utcDate).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}</span><span className="v4HighlightTeams">{x.row.fixture.home.name} · {x.row.fixture.away.name}</span><h3>{marketLabel(x.row,x.market)}</h3><div><b>{pct(x.market.probability)}</b><small>probabilità</small></div><em>Affidabilità {trust(x.market.confidence)}</em></button><button className={selected?'selected':''} aria-pressed={selected} onClick={()=>toggle(x.row,x.market)}>{selected?'✓ Rimuovi dal sistema':'+ Aggiungi al sistema'}</button></article>})}</div>:<div className="v4Empty">Nessun pronostico supera i criteri di affidabilità.</div>}</section>
 <section className="v4Filters"><div className="v4Chips">{(['Tutte','Più affidabili','Gol','Over/Under','Marcatori']as SimpleFilter[]).map(x=><button key={x} className={filter===x?'on':''} onClick={()=>setFilter(x)}>{x}</button>)}</div><label className="v4Search"><span>Cerca squadra</span><input value={team} onChange={e=>setTeam(e.target.value)} placeholder="Es. Como"/></label></section>
 <MatchdayList rows={filtered} bag={bag} toggle={toggle} open={open}/></>;
}

function MatchdayList({rows,bag,toggle,open}:{rows:Row[];bag:SystemPick[];toggle:(r:Row,m:Market)=>void;open:(r:Row)=>void}){
 const groups=groupByMatchday(rows);if(!groups.length)return <div className="v4Empty">Nessuna partita corrisponde ai filtri.</div>;
 return <div className="v4Matchdays">{groups.map(([label,dates],idx)=><details className="v4Matchday" key={label} open={idx===0}><summary><span><small>SERIE A</small><b>{label}</b><i>{matchdayDate(dates)}</i></span><em>{dates.reduce((n,[,rs])=>n+rs.length,0)} partite <strong className="v4Chevron">⌄</strong></em></summary><div>{dates.map(([date,rs],dateIndex)=><section className={`v4Date ${dateIndex%2?'even':'odd'}`} key={date}><h3>{date}</h3>{rs.map((r,i)=><CompactMatch key={r.fixture.id} row={r} index={i} bag={bag} toggle={toggle} open={()=>open(r)}/>)}</section>)}</div></details>)}</div>;
}

function CompactMatch({row,index,bag,toggle,open}:{row:Row;index:number;bag:SystemPick[];toggle:(r:Row,m:Market)=>void;open:()=>void}){
 const top=[...row.markets].filter(m=>m.status==='ACTIVE').sort((a,b)=>reliability(b)-reliability(a))[0];const selected=top?bag.some(p=>p.id===pid(row,top)):false;
 return <article className={`v4Match ${index%2?'even':'odd'}`}><button className="v4MatchMain" onClick={open}><span className="v4Time">{new Date(row.fixture.utcDate).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}</span><span className="v4Teams"><b>{row.fixture.home.name}</b><i>vs</i><b>{row.fixture.away.name}</b></span><strong>›</strong></button>{top?<div className="v4TopPick"><button onClick={open}><span>{marketLabel(row,top)}</span><b>{pct(top.probability)}</b><em>Affidabilità {trust(top.confidence)}</em></button><button className={selected?'selected':''} aria-pressed={selected} onClick={()=>toggle(row,top)}>{selected?'✓ Rimuovi':'+ Sistema'}</button></div>:<div className="v4NoPick">Nessun pronostico consigliato</div>}</article>;
}

function Fixtures({rows,open}:{rows:Row[];open:(r:Row)=>void}){const[q,setQ]=useState('');const filtered=rows.filter(r=>`${r.fixture.home.name} ${r.fixture.away.name}`.toLowerCase().includes(q.toLowerCase()));return <><label className="v4Search standalone"><span>Cerca squadra</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Es. Napoli"/></label>{groupByMatchday(filtered).map(([label,dates],idx)=><details className="v4Matchday" key={label} open={idx===0}><summary><span><small>SERIE A</small><b>{label}</b><i>{matchdayDate(dates)}</i></span><em>{dates.reduce((n,[,rs])=>n+rs.length,0)} partite <strong className="v4Chevron">⌄</strong></em></summary>{dates.map(([date,rs],dateIndex)=><section className={`v4Date ${dateIndex%2?'even':'odd'}`} key={date}><h3>{date}</h3>{rs.map((r,i)=><button className={`v4Fixture ${i%2?'even':'odd'}`} key={r.fixture.id} onClick={()=>open(r)}><span>{new Date(r.fixture.utcDate).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}</span><b>{r.fixture.home.name} <i>vs</i> {r.fixture.away.name}</b><strong>›</strong></button>)}</section>)}</details>)}</>}

function MatchDetail({row,bag,toggle,back,openSystem}:{row:Row;bag:SystemPick[];toggle:(r:Row,m:Market)=>void;back:()=>void;openSystem:()=>void}){const[c,setC]=useState('Esito');const active=row.markets.filter(m=>m.status==='ACTIVE'),top=[...active].sort((a,b)=>reliability(b)-reliability(a))[0],cats=['Esito','Gol','Over / Under','Gol squadra','Risultati','Marcatori'];const shown=row.markets.filter(m=>marketCategory(m)===c);return <div className="mShell v4Shell"><header className="v4Header"><button className="v4Icon" onClick={back} aria-label="Indietro">←</button><div><small>PARTITA</small><h1>{row.fixture.home.name} vs {row.fixture.away.name}</h1></div></header><main className="v4Main"><section className="v4DetailHead"><span>{day(row.fixture.utcDate)}</span><h2>{row.fixture.home.name} <i>vs</i> {row.fixture.away.name}</h2></section>{top?<section className="v4Advice"><small>PRONOSTICO PRINCIPALE</small><h3>{marketLabel(row,top)}</h3><div className="v4AdviceMetric"><b>{pct(top.probability)}</b><span>probabilità stimata</span></div><em>Affidabilità {trust(top.confidence)}</em><button className={bag.some(p=>p.id===pid(row,top))?'selected':''} onClick={()=>toggle(row,top)}>{bag.some(p=>p.id===pid(row,top))?'✓ Rimuovi dal sistema':'+ Aggiungi al sistema'}</button></section>:<section className="v4NoAdvice"><b>Nessun pronostico consigliato</b></section>}
 <section className="v4Markets"><h2>Altri pronostici</h2><div className="v4MarketTabs">{cats.map(x=><button key={x} className={c===x?'on':''} onClick={()=>setC(x)}>{x}</button>)}</div>{shown.length?shown.map(m=><MarketOption key={`${m.market}-${m.selection}`} row={row} market={m} selected={bag.some(p=>p.id===pid(row,m))} toggle={()=>toggle(row,m)}/>):<div className="v4Empty">Nessun pronostico disponibile.</div>}</section>
 <details className="v4Advanced"><summary>Statistiche e analisi</summary><MatchIntelligence fixtureId={row.fixture.id}/></details></main>{bag.length>0&&<button className="v4Slip" onClick={openSystem}><span><b>{bag.length}</b> {bag.length===1?'selezione':'selezioni'}</span><strong>Apri sistema ›</strong></button>}</div>}

function MarketOption({row,market,selected,toggle}:{row:Row;market:Market;selected:boolean;toggle:()=>void}){return <article className={`v4MarketOption ${selected?'selected':''}`}><div><b>{marketLabel(row,market)}</b><span>{pct(market.probability)} probabilità · Affidabilità {trust(market.confidence)}</span></div><button aria-pressed={selected} onClick={toggle}>{selected?'✓ Rimuovi':'+ Aggiungi'}</button></article>}

function Drawer({tab,mode,close,navigate,setMode}:{tab:Tab;mode:Mode;close:()=>void;navigate:(t:Tab)=>void;setMode:(m:Mode)=>void}){return <div className="mDrawerLayer" role="dialog" aria-modal="true" onClick={close}><aside className="mDrawer v4Drawer" onClick={e=>e.stopPropagation()}><div className="mDrawerHead"><div><small>FPS FORESIGHT</small><b>{RELEASE}</b></div><button aria-label="Chiudi menu" onClick={close}>×</button></div><nav>{(['Home','Partite','Sistema','I miei sistemi','Storico','Statistiche','Impostazioni']as Tab[]).map(t=><button key={t} className={tab===t?'on':''} onClick={()=>navigate(t)}>{t}<span>›</span></button>)}</nav><details className="v4DataOptions"><summary>Origine dei dati</summary><button className={mode==='PRESEASON'?'on':''} onClick={()=>setMode('PRESEASON')}>Inizio stagione · usa anche storico</button><button className={mode==='LIVE'?'on':''} onClick={()=>setMode('LIVE')}>Solo stagione corrente</button></details><footer><small>Le percentuali sono stime, non certezze.</small></footer></aside></div>}

function SavedSystems(){const[items,setItems]=useState<any[]>([]);useEffect(()=>{void request(`${API}/v2/history/systems`).then(x=>setItems(Array.isArray(x)?x:[])).catch(()=>setItems([]))},[]);return <section className="mPanel"><h2>I miei sistemi</h2>{items.length?items.map(s=><article className="mSaved" key={s.id}><span><b>{s.selections?.length||0} selezioni</b><small>{s.played?'Giocato realmente':s.simulated?'Simulazione':'Non giocato'} · €{Number(s.totalCost||0).toFixed(2)}</small></span><strong>{s.status}</strong></article>):<div className="v4Empty">Non hai ancora salvato sistemi.</div>}</section>}
function Settings({mode}:{mode:Mode}){return <section className="mPanel"><h2>Impostazioni</h2><div className="mInfoRow"><span>Release</span><b>{RELEASE}</b></div><div className="mInfoRow"><span>Dati</span><b>{mode==='PRESEASON'?'Storico + stagione corrente':'Stagione corrente'}</b></div></section>}

type Highlight={kind:string;icon:string;tone:string;row:Row;market:Market;score:number};
function dailyHighlights(rows:Row[]):Highlight[]{const all=rows.flatMap(row=>row.markets.filter(m=>m.status==='ACTIVE').map(m=>({row,market:m,score:reliability(m)}))).filter(x=>x.market.confidence>=.5&&x.market.dataQuality>=.5),used=new Set<string>(),out:Highlight[]=[];const take=(kind:string,icon:string,tone:string,p:(x:(typeof all)[number])=>boolean)=>{const x=[...all].filter(p).filter(v=>!used.has(pid(v.row,v.market))).sort((a,b)=>b.score-a.score)[0];if(x){used.add(pid(x.row,x.market));out.push({kind,icon,tone,...x})}};take('Pick del giorno','🛡️','safe',x=>x.market.probability>=.55&&x.market.confidence>=.6);take('Alternativa','◆','alt',x=>x.market.probability>=.5&&x.market.confidence>=.55);take('Sorpresa','⚡','surprise',x=>x.market.probability>=.2&&x.market.probability<.55&&x.market.confidence>=.55);take('Tentativo','🎯','try',x=>(x.market.market==='EXACT_SCORE'||x.market.market.includes('SCORER'))&&x.market.probability>=.05&&x.market.probability<=.3);return out.slice(0,4)}
function reliability(m:Market){return m.probability*.45+m.confidence*.3+m.dataQuality*.25}
function trust(v:number){return v>=.78?'molto alta':v>=.68?'alta':v>=.55?'media':'bassa'}
function friendlyKind(v:string){return v==='Pick del giorno'?'Più affidabile':v}
function pid(r:Row,m:Market){return`${r.fixture.id}|${m.market}|${m.selection}`}
function pick(r:Row,m:Market):SystemPick{return{id:pid(r,m),fixtureId:r.fixture.id,market:m.market,selection:m.selection,eventAt:r.fixture.utcDate,probability:m.probability,confidence:m.confidence,dataQuality:m.dataQuality,fairOdds:m.fairOdds,period:m.period,metric:m.metric,operator:m.operator,threshold:m.threshold,outcome:m.outcome,homeName:r.fixture.home.name,awayName:r.fixture.away.name}}
function marketLabel(r:Row,m:Market){const s=String(m.selection).toUpperCase();if(m.market==='1X2')return s==='1'||s==='HOME'?`Vince ${r.fixture.home.name}`:s==='2'||s==='AWAY'?`Vince ${r.fixture.away.name}`:'Pareggio';if(m.market==='BTTS')return s==='GOAL'?'Entrambe segnano':'Almeno una non segna';if(m.market==='EXACT_SCORE')return`Risultato esatto ${m.selection}`;if(m.market.includes('SCORER'))return`${m.selection} marcatore`;return String(m.selection).replaceAll('_',' ').replace(/\bHOME\b/g,r.fixture.home.name).replace(/\bAWAY\b/g,r.fixture.away.name).replace(/OVER/g,'Over').replace(/UNDER/g,'Under')}
function marketCategory(m:Market){if(['1X2','DOUBLE_CHANCE','DRAW_NO_BET','WIN_MARGIN'].includes(m.market))return'Esito';if(m.market==='BTTS'||['MULTIGOAL','GOALS_PARITY'].includes(m.market))return'Gol';if(m.market.startsWith('OVER_UNDER'))return'Over / Under';if(m.market.startsWith('HOME_GOALS')||m.market.startsWith('AWAY_GOALS'))return'Gol squadra';if(m.market==='EXACT_SCORE')return'Risultati';if(m.market.includes('SCORER'))return'Marcatori';return'Altro'}
function shortRows(rows:Row[]):Row[]{return rows.map(r=>({...r,fixture:{...r.fixture,home:{...r.fixture.home,name:shortTeam(r.fixture.home.name)},away:{...r.fixture.away,name:shortTeam(r.fixture.away.name)}}}))}
function shortTeam(name:string){const n=name.trim(),a:Record<string,string>={'FC Internazionale Milano':'Inter','Internazionale':'Inter','AC Milan':'Milan','SSC Napoli':'Napoli','AS Roma':'Roma','SS Lazio':'Lazio','ACF Fiorentina':'Fiorentina','Atalanta BC':'Atalanta','Bologna FC 1909':'Bologna','Cagliari Calcio':'Cagliari','Como 1907':'Como','Genoa CFC':'Genoa','Juventus FC':'Juventus','US Lecce':'Lecce','Parma Calcio 1913':'Parma','Torino FC':'Torino','Udinese Calcio':'Udinese','Hellas Verona FC':'Verona','US Sassuolo Calcio':'Sassuolo','US Cremonese':'Cremonese','Pisa SC':'Pisa'};return a[n]||n.replace(/\b(FC|AC|SSC|SS|AS|BC|CFC|US|Calcio|1907|1909|1913)\b/gi,'').replace(/\s+/g,' ').trim()||n}
function groupByMatchday(rows:Row[]):[string,[string,Row[]][]][]{const by=new Map<string,Row[]>();rows.forEach(r=>{const md=(r.fixture as any).matchday;const key=Number.isFinite(Number(md))?`Giornata ${Number(md)}`:'Prossimo turno';by.set(key,[...(by.get(key)||[]),r])});return[...by.entries()].sort((a,b)=>{const na=Number(a[0].match(/\d+/)?.[0]||999),nb=Number(b[0].match(/\d+/)?.[0]||999);return na-nb}).map(([k,rs])=>[k,groupDates(rs)])}
function groupDates(rows:Row[]):[string,Row[]][]{const m=new Map<string,Row[]>();[...rows].sort((a,b)=>+new Date(a.fixture.utcDate)-+new Date(b.fixture.utcDate)).forEach(r=>{const k=day(r.fixture.utcDate);m.set(k,[...(m.get(k)||[]),r])});return[...m.entries()]}
function compactDate(v:string){return new Date(v).toLocaleDateString('it-IT',{weekday:'short',day:'2-digit',month:'short'}).replaceAll('.','')}
function matchdayDate(dates:[string,Row[]][]){const all=dates.flatMap(([,rs])=>rs).map(r=>new Date(r.fixture.utcDate)).sort((a,b)=>+a-+b);if(!all.length)return'';const first=all[0],last=all[all.length-1];const f=first.toLocaleDateString('it-IT',{day:'2-digit',month:'short'}).replaceAll('.','');const l=last.toLocaleDateString('it-IT',{day:'2-digit',month:'short'}).replaceAll('.','');return f===l?f:`${f} – ${l}`}
