import React,{useEffect,useMemo,useState}from'react';
import HistoryDashboard from'../../web/app/HistoryDashboard';
import StatsDashboard from'../../web/app/StatsDashboard';
import SystemBuilderPanel,{type SystemPick}from'../../web/app/SystemBuilderPanel';
import MatchIntelligence from'../../web/app/MatchIntelligence';
import DataFreshnessBar from'./DataFreshnessBar';
import type{Market,Row}from'./mobile-types';
import{day,featured,pct}from'./mobile-types';

const API='http://localhost:4000',RELEASE='v1.3.0-beta.1';
type Tab='Home'|'Partite'|'Sistema'|'Storico'|'Statistiche'|'I miei sistemi'|'Impostazioni';
type Mode='PRESEASON'|'LIVE';
type SimpleFilter='Tutte'|'Più affidabili'|'Gol'|'Over/Under'|'Marcatori';
type PremiumPick=SystemPick&{label?:string;fixtureLabel?:string;marketLabel?:string};

async function request(url:string,init?:RequestInit){const r=await fetch(url,init),b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.message||`${r.status}`);return b}
async function post(url:string,body:unknown){return request(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)})}

export default function PremiumHome(){
 const[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[bag,setBag]=useState<SystemPick[]>([]),[tab,setTab]=useState<Tab>('Home'),[detail,setDetail]=useState<Row|null>(null),[drawer,setDrawer]=useState(false),[mode,setMode]=useState<Mode>('PRESEASON'),[toast,setToast]=useState(''),[conflict,setConflict]=useState('');
 const load=()=>{setLoading(true);setError('');const endpoint=mode==='PRESEASON'?'/v2/preseason':'/v2/predictions';void request(`${API}${endpoint}?competition=SA&persist=true`).then(b=>setRows(shortRows(b.data||[]))).catch(e=>setError(e.message)).finally(()=>setLoading(false))};
 useEffect(load,[mode]);
 const toggle=async(row:Row,m:Market)=>{const p=pick(row,m),exists=bag.some(x=>x.id===p.id);if(exists){setBag(x=>x.filter(i=>i.id!==p.id));setToast('Rimosso dal sistema');setConflict('');window.setTimeout(()=>setToast(''),1400);return}try{const analysis=await post(`${API}/v2/systems/analyze`,{selections:[...bag,p]});if(analysis?.status==='INCOMPATIBLE'){const pair=(analysis.incompatible||[]).find((x:any)=>x.left===p.id||x.right===p.id);const otherId=pair?(pair.left===p.id?pair.right:pair.left):undefined;const other=bag.find(x=>x.id===otherId)as PremiumPick|undefined;const msg=`Non puoi aggiungere ${p.label||p.selection}${other?` insieme a ${other.label||other.selection}`:''}: le due scelte sono incompatibili.`;setConflict(msg);setToast('Selezione non aggiunta');window.setTimeout(()=>setToast(''),1800);return}setBag(x=>[...x,p]);setConflict('');setToast(analysis?.correlations?.some((x:any)=>x.level==='HIGH')?'Aggiunta · correlazione alta rilevata':'Aggiunto al sistema');window.setTimeout(()=>setToast(''),1600)}catch(e:any){setConflict(`Controllo incompatibilità non disponibile: ${e?.message||e}`)}};
 const removePick=(id:string)=>setBag(x=>x.filter(p=>p.id!==id));
 const available=useMemo(()=>rows.flatMap(r=>featured(r).filter(m=>m.status==='ACTIVE').map(m=>pick(r,m))),[rows]);
 if(detail)return <PremiumMatchDetail row={detail} bag={bag} toggle={toggle} back={()=>setDetail(null)} openSystem={()=>{setDetail(null);setTab('Sistema')}}/>;
 return <div className="pShell">
  <PremiumHeader tab={tab} setTab={setTab} openMenu={()=>setDrawer(true)}/>
  {drawer&&<Drawer tab={tab} mode={mode} close={()=>setDrawer(false)} navigate={t=>{setTab(t);setDrawer(false)}} setMode={m=>{setMode(m);setTab('Home');setDrawer(false)}}/>}
  {tab==='Home'&&<PremiumHero onRefresh={load}/>} {tab!=='Home'&&<DataFreshnessBar onRefresh={load}/>} 
  {conflict&&<div className="pConflict" role="alert"><span>!</span><div><b>Scelta incompatibile</b><small>{conflict}</small></div><button onClick={()=>setConflict('')} aria-label="Chiudi">×</button></div>}
  <main className="pMain">{tab==='Home'&&<Home rows={rows} bag={bag} loading={loading} error={error} retry={load} toggle={toggle} open={setDetail} removePick={removePick} openSystem={()=>setTab('Sistema')}/>} {tab==='Partite'&&<Fixtures rows={rows} open={setDetail}/>} {tab==='Sistema'&&<SystemBuilderPanel bag={bag} setBag={setBag} available={available}/>} {tab==='Storico'&&<HistoryDashboard/>}{tab==='Statistiche'&&<StatsDashboard/>}{tab==='I miei sistemi'&&<SavedSystems/>}{tab==='Impostazioni'&&<Settings mode={mode}/>}</main>
  {toast&&<div className="pToast" role="status">{toast}</div>}
  {bag.length>0&&tab!=='Sistema'&&<button className="pSlipMobile" onClick={()=>setTab('Sistema')}><span><b>{bag.length}</b> {bag.length===1?'selezione':'selezioni'}</span><strong>Apri sistema ›</strong></button>}
  <PremiumBottom tab={tab} setTab={setTab} count={bag.length}/>
 </div>
}

function PremiumHeader({tab,setTab,openMenu}:{tab:Tab;setTab:(t:Tab)=>void;openMenu:()=>void}){const nav:Tab[]=['Home','Partite','Sistema','Storico','Statistiche'];return <header className="pHeader"><button className="pMenu" onClick={openMenu} aria-label="Menu">☰</button><button className="pBrand" onClick={()=>setTab('Home')}><img src="/src/premium-assets/fps-mark.svg" alt=""/><span><b>FPS</b><small>FOOTBALL<br/>PREDICTION SYSTEM</small></span></button><nav>{nav.map(t=><button key={t} className={tab===t?'on':''} onClick={()=>setTab(t)}>{t==='Home'?'Panoramica':t}</button>)}</nav><span className="pVersion">{RELEASE}</span></header>}
function PremiumHero({onRefresh}:{onRefresh:()=>void}){return <section className="pHero"><div className="pHeroInner"><div><small>FOOTBALL PREDICTION SYSTEM</small><h1>Analisi. Probabilità. Valore.</h1><p>Il vantaggio è nei dati.</p><div className="pHeroActions"><button onClick={onRefresh}>Aggiorna dati</button><span>Stime probabilistiche · nessuna certezza</span></div></div></div></section>}

function Home({rows,bag,loading,error,retry,toggle,open,removePick,openSystem}:{rows:Row[];bag:SystemPick[];loading:boolean;error:string;retry:()=>void;toggle:(r:Row,m:Market)=>Promise<void>;open:(r:Row)=>void;removePick:(id:string)=>void;openSystem:()=>void}){
 const[filter,setFilter]=useState<SimpleFilter>('Tutte'),[team,setTeam]=useState('');const highlights=useMemo(()=>dailyHighlights(rows),[rows]);const filtered=useMemo(()=>rows.filter(r=>{if(team&&!`${r.fixture.home.name} ${r.fixture.away.name}`.toLowerCase().includes(team.toLowerCase()))return false;if(filter==='Più affidabili')return r.markets.some(m=>m.status==='ACTIVE'&&m.confidence>=.7);if(filter==='Gol')return r.markets.some(m=>m.status==='ACTIVE'&&['BTTS','MULTIGOAL','GOALS_PARITY'].includes(m.market));if(filter==='Over/Under')return r.markets.some(m=>m.status==='ACTIVE'&&m.market.startsWith('OVER_UNDER'));if(filter==='Marcatori')return r.markets.some(m=>m.status==='ACTIVE'&&m.market.includes('SCORER'));return true}),[rows,filter,team]);
 if(loading)return <div className="pState"><b>Analisi delle partite…</b><span>Sto preparando le opportunità disponibili.</span></div>;
 return <>{error&&<div className="pError"><b>Dati non disponibili</b><span>{error}</span><button onClick={retry}>Riprova</button></div>}<section className="pHighlights"><div className="pSectionTitle"><div><small>SELEZIONE AUTOMATICA</small><h2>In evidenza</h2></div><span>fino a 4 opportunità</span></div>{highlights.length?<div className="pHighlightGrid">{highlights.map(x=>{const selected=bag.some(p=>p.id===pid(x.row,x.market));return <article className={`pHighlight ${x.tone}`} key={`${x.kind}-${pid(x.row,x.market)}`}><button className="pHighlightBody" onClick={()=>open(x.row)}><span className="pHighlightTag">{x.icon} {friendlyKind(x.kind)}</span><small>{compactDate(x.row.fixture.utcDate)} · {time(x.row.fixture.utcDate)}</small><strong>{x.row.fixture.home.name} vs {x.row.fixture.away.name}</strong><h3>{marketLabel(x.row,x.market)}</h3><div className="pMetric"><b>{pct(x.market.probability)}</b><span>probabilità</span></div><em>● Affidabilità {trust(x.market.confidence)}</em></button><button className={selected?'selected':''} aria-pressed={selected} onClick={()=>void toggle(x.row,x.market)}>{selected?'✓ Rimuovi dal sistema':'+ Aggiungi al sistema'}</button></article>})}</div>:<div className="pEmpty">Nessun pronostico supera i criteri di affidabilità.</div>}</section>
 <section className="pFilters"><div>{(['Tutte','Più affidabili','Gol','Over/Under','Marcatori']as SimpleFilter[]).map(x=><button key={x} className={filter===x?'on':''} onClick={()=>setFilter(x)}>{x}</button>)}</div><label><input value={team} onChange={e=>setTeam(e.target.value)} placeholder="Cerca squadra…"/><span>⌕</span></label></section>
 <div className="pContentGrid"><section className="pLeague"><div className="pLeagueTitle"><span className="pSerieBadge">A</span><div><small>CAMPIONATO</small><b>SERIE A</b></div></div><MatchdayList rows={filtered} bag={bag} toggle={toggle} open={open}/></section><SystemSlip bag={bag} removePick={removePick} openSystem={openSystem}/></div></>}

function SystemSlip({bag,removePick,openSystem}:{bag:SystemPick[];removePick:(id:string)=>void;openSystem:()=>void}){return <aside className="pSystemSlip"><header><div><small>IL TUO SISTEMA</small><b>{bag.length}</b></div>{bag.length>0&&<button onClick={()=>bag.forEach(p=>removePick(p.id))} aria-label="Svuota sistema">⌫</button>}</header>{bag.length?<div className="pSlipRows">{bag.map((raw,i)=>{const p=raw as PremiumPick;return <article key={p.id}><i/><div><small>{p.fixtureLabel||compactDate(p.eventAt)}</small><b>{p.label||humanSelection(p.selection)}</b><span>{p.marketLabel||humanMarket(p.market)}</span></div><button onClick={()=>removePick(p.id)} aria-label={`Rimuovi ${p.label||p.selection}`}>×</button>{p.fixed&&<em>FISSA</em>}</article>})}</div>:<div className="pSlipEmpty"><b>Nessuna selezione</b><span>Aggiungi un pronostico dalle card o dalle partite.</span></div>}<footer><div><span>Selezioni</span><b>{bag.length}</b></div><div><span>Stato</span><b>{bag.length?'Pronto da configurare':'Vuoto'}</b></div><button disabled={!bag.length} onClick={openSystem}>Configura sistema</button></footer></aside>}

function MatchdayList({rows,bag,toggle,open}:{rows:Row[];bag:SystemPick[];toggle:(r:Row,m:Market)=>Promise<void>;open:(r:Row)=>void}){const groups=groupByMatchday(rows);if(!groups.length)return <div className="pEmpty">Nessuna partita corrisponde ai filtri.</div>;return <div className="pMatchdays">{groups.map(([label,dates],idx)=><details className="pMatchday" key={label} open={idx===0}><summary><span><b>{label}</b><small>{matchdayDate(dates)}</small></span><em>{dates.reduce((n,[,rs])=>n+rs.length,0)} partite</em><i>⌄</i></summary>{dates.map(([date,rs])=><section className="pDate" key={date}><h3>{date}</h3>{rs.map((r,i)=><PremiumMatch key={r.fixture.id} row={r} index={i} bag={bag} toggle={toggle} open={()=>open(r)}/>)}</section>)}</details>)}</div>}
function PremiumMatch({row,index,bag,toggle,open}:{row:Row;index:number;bag:SystemPick[];toggle:(r:Row,m:Market)=>Promise<void>;open:()=>void}){const top=[...row.markets].filter(m=>m.status==='ACTIVE').sort((a,b)=>reliability(b)-reliability(a))[0],selected=top?bag.some(p=>p.id===pid(row,top)):false;return <article className={`pMatch ${index%2?'even':'odd'}`}><button className="pMatchTeams" onClick={open}><span>{time(row.fixture.utcDate)}</span><div><b>{row.fixture.home.name}</b><i>vs</i><b>{row.fixture.away.name}</b></div><strong>›</strong></button>{top?<div className="pMatchPick"><button onClick={open}><b>{marketLabel(row,top)}</b><span>Affidabilità {trust(top.confidence)}</span></button><strong>{pct(top.probability)}</strong><button className={selected?'selected':''} onClick={()=>void toggle(row,top)}>{selected?'✓ Nel sistema':'+ Sistema'}</button></div>:<div className="pNoBet">Nessun pronostico consigliato</div>}</article>}

function Fixtures({rows,open}:{rows:Row[];open:(r:Row)=>void}){const[q,setQ]=useState(''),filtered=rows.filter(r=>`${r.fixture.home.name} ${r.fixture.away.name}`.toLowerCase().includes(q.toLowerCase()));return <section className="pPagePanel"><div className="pPageHead"><div><small>SERIE A</small><h2>Partite</h2></div><label><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cerca squadra…"/></label></div>{groupByMatchday(filtered).map(([label,dates],idx)=><details className="pMatchday" key={label} open={idx===0}><summary><span><b>{label}</b><small>{matchdayDate(dates)}</small></span><em>{dates.reduce((n,[,rs])=>n+rs.length,0)} partite</em><i>⌄</i></summary>{dates.map(([date,rs])=><section className="pDate" key={date}><h3>{date}</h3>{rs.map((r,i)=><button className={`pFixture ${i%2?'even':'odd'}`} key={r.fixture.id} onClick={()=>open(r)}><span>{time(r.fixture.utcDate)}</span><b>{r.fixture.home.name} <i>vs</i> {r.fixture.away.name}</b><strong>›</strong></button>)}</section>)}</details>)}</section>}

function PremiumMatchDetail({row,bag,toggle,back,openSystem}:{row:Row;bag:SystemPick[];toggle:(r:Row,m:Market)=>Promise<void>;back:()=>void;openSystem:()=>void}){const[c,setC]=useState('Esito'),active=row.markets.filter(m=>m.status==='ACTIVE'),top=[...active].sort((a,b)=>reliability(b)-reliability(a))[0],cats=['Esito','Gol','Over / Under','Gol squadra','Risultati','Marcatori'],shown=row.markets.filter(m=>marketCategory(m)===c);return <div className="pShell"><PremiumHeader tab="Partite" setTab={()=>{}} openMenu={()=>{}}/><main className="pMain pDetail"><button className="pBack" onClick={back}>← Torna alle partite</button><section className="pDetailHero"><small>{day(row.fixture.utcDate)} · {time(row.fixture.utcDate)}</small><h1>{row.fixture.home.name} <i>vs</i> {row.fixture.away.name}</h1>{top&&<div className="pPrimaryPick"><span>PRONOSTICO PRINCIPALE</span><h2>{marketLabel(row,top)}</h2><b>{pct(top.probability)}</b><small>probabilità · Affidabilità {trust(top.confidence)}</small><button className={bag.some(p=>p.id===pid(row,top))?'selected':''} onClick={()=>void toggle(row,top)}>{bag.some(p=>p.id===pid(row,top))?'✓ Rimuovi dal sistema':'+ Aggiungi al sistema'}</button></div>}</section><section className="pMarkets"><div className="pMarketTabs">{cats.map(x=><button key={x} className={c===x?'on':''} onClick={()=>setC(x)}>{x}</button>)}</div>{shown.length?shown.map(m=><MarketOption key={`${m.market}-${m.selection}`} row={row} market={m} selected={bag.some(p=>p.id===pid(row,m))} toggle={()=>void toggle(row,m)}/>):<div className="pEmpty">Nessun pronostico disponibile.</div>}</section><details className="pAdvanced"><summary>Statistiche e analisi</summary><MatchIntelligence fixtureId={row.fixture.id}/></details></main>{bag.length>0&&<button className="pSlipMobile" onClick={openSystem}><span><b>{bag.length}</b> selezioni</span><strong>Apri sistema ›</strong></button>}</div>}
function MarketOption({row,market,selected,toggle}:{row:Row;market:Market;selected:boolean;toggle:()=>void}){return <article className={`pMarket ${selected?'selected':''}`}><div><b>{marketLabel(row,market)}</b><span>{pct(market.probability)} probabilità · Affidabilità {trust(market.confidence)}</span></div><button onClick={toggle}>{selected?'✓ Rimuovi':'+ Aggiungi'}</button></article>}

function PremiumBottom({tab,setTab,count}:{tab:Tab;setTab:(t:Tab)=>void;count:number}){return <nav className="pBottom"><button className={tab==='Home'?'on':''} onClick={()=>setTab('Home')}><span>⌂</span><small>Home</small></button><button className={tab==='Partite'?'on':''} onClick={()=>setTab('Partite')}><span>⚽</span><small>Partite</small></button><button className={`pBottomMain ${tab==='Sistema'?'on':''}`} onClick={()=>setTab('Sistema')}><span>＋</span><small>Sistema</small>{count>0&&<i>{count}</i>}</button><button className={tab==='Storico'?'on':''} onClick={()=>setTab('Storico')}><span>◷</span><small>Storico</small></button></nav>}
function Drawer({tab,mode,close,navigate,setMode}:{tab:Tab;mode:Mode;close:()=>void;navigate:(t:Tab)=>void;setMode:(m:Mode)=>void}){return <div className="pDrawerLayer" onClick={close}><aside className="pDrawer" onClick={e=>e.stopPropagation()}><header><div className="pBrand"><img src="/src/premium-assets/fps-mark.svg" alt=""/><span><b>FPS</b><small>{RELEASE}</small></span></div><button onClick={close}>×</button></header><nav>{(['Home','Partite','Sistema','I miei sistemi','Storico','Statistiche','Impostazioni']as Tab[]).map(t=><button key={t} className={tab===t?'on':''} onClick={()=>navigate(t)}>{t}<span>›</span></button>)}</nav><details><summary>Origine dei dati</summary><button className={mode==='PRESEASON'?'on':''} onClick={()=>setMode('PRESEASON')}>Storico + stagione corrente</button><button className={mode==='LIVE'?'on':''} onClick={()=>setMode('LIVE')}>Solo stagione corrente</button></details></aside></div>}
function SavedSystems(){const[items,setItems]=useState<any[]>([]);useEffect(()=>{void request(`${API}/v2/history/systems`).then(x=>setItems(Array.isArray(x)?x:[])).catch(()=>setItems([]))},[]);return <section className="pPagePanel"><div className="pPageHead"><div><small>ARCHIVIO</small><h2>I miei sistemi</h2></div></div>{items.length?items.map(s=><article className="pSaved" key={s.id}><span><b>{s.selections?.length||0} selezioni</b><small>{s.played?'Giocato realmente':s.simulated?'Simulazione':'Non giocato'} · €{Number(s.totalCost||0).toFixed(2)}</small></span><strong>{s.status}</strong></article>):<div className="pEmpty">Non hai ancora salvato sistemi.</div>}</section>}
function Settings({mode}:{mode:Mode}){return <section className="pPagePanel"><div className="pPageHead"><div><small>APP</small><h2>Impostazioni</h2></div></div><div className="pSettingsRow"><span>Release</span><b>{RELEASE}</b></div><div className="pSettingsRow"><span>Dati</span><b>{mode==='PRESEASON'?'Storico + stagione corrente':'Stagione corrente'}</b></div></section>}

type Highlight={kind:string;icon:string;tone:string;row:Row;market:Market;score:number};
function dailyHighlights(rows:Row[]):Highlight[]{const all=rows.flatMap(row=>row.markets.filter(m=>m.status==='ACTIVE').map(m=>({row,market:m,score:reliability(m)}))).filter(x=>x.market.confidence>=.5&&x.market.dataQuality>=.5),used=new Set<string>(),out:Highlight[]=[];const take=(kind:string,icon:string,tone:string,p:(x:(typeof all)[number])=>boolean)=>{const x=[...all].filter(p).filter(v=>!used.has(pid(v.row,v.market))).sort((a,b)=>b.score-a.score)[0];if(x){used.add(pid(x.row,x.market));out.push({kind,icon,tone,...x})}};take('Pick del giorno','🏆','safe',x=>x.market.probability>=.55&&x.market.confidence>=.6);take('Alternativa','★','alt',x=>x.market.probability>=.5&&x.market.confidence>=.55);take('Sorpresa','⚡','surprise',x=>x.market.probability>=.2&&x.market.probability<.55&&x.market.confidence>=.55);take('Tentativo','🎯','try',x=>(x.market.market==='EXACT_SCORE'||x.market.market.includes('SCORER'))&&x.market.probability>=.05&&x.market.probability<=.3);return out.slice(0,4)}
function reliability(m:Market){return m.probability*.45+m.confidence*.3+m.dataQuality*.25}function trust(v:number){return v>=.78?'molto alta':v>=.68?'alta':v>=.55?'media':'bassa'}function friendlyKind(v:string){return v==='Pick del giorno'?'Più affidabile':v}function pid(r:Row,m:Market){return`${r.fixture.id}|${m.market}|${m.selection}`}
function pick(r:Row,m:Market):PremiumPick{return{id:pid(r,m),fixtureId:r.fixture.id,market:m.market,selection:m.selection,eventAt:r.fixture.utcDate,probability:m.probability,confidence:m.confidence,dataQuality:m.dataQuality,fairOdds:m.fairOdds,period:m.period,metric:m.metric,operator:m.operator,threshold:m.threshold,outcome:m.outcome,teamSide:(m as any).teamSide,playerId:(m as any).playerId,label:marketLabel(r,m),fixtureLabel:`${r.fixture.home.name} vs ${r.fixture.away.name}`,marketLabel:humanMarket(m.market)}}
function marketLabel(r:Row,m:Market){if(m.market==='1X2')return m.selection==='1'?`Vince ${r.fixture.home.name}`:m.selection==='2'?`Vince ${r.fixture.away.name}`:'Pareggio';if(m.market==='BTTS')return m.selection==='GOAL'?'Entrambe segnano':'Almeno una non segna';if(m.market==='EXACT_SCORE')return`Risultato esatto ${m.selection}`;if(m.market.includes('SCORER'))return`${m.selection} marcatore`;if(m.market.startsWith('HOME_GOALS'))return`${r.fixture.home.name} ${humanSelection(m.selection)}`;if(m.market.startsWith('AWAY_GOALS'))return`${r.fixture.away.name} ${humanSelection(m.selection)}`;return humanSelection(m.selection)}
function humanSelection(v:string){return String(v).replaceAll('_',' ').replace(/\bAWAY\b/gi,'Squadra ospite').replace(/\bHOME\b/gi,'Squadra di casa').replace(/OVER/gi,'Over').replace(/UNDER/gi,'Under')}function humanMarket(v:string){if(v==='1X2')return'Esito partita';if(v==='BTTS')return'Entrambe segnano';if(v==='EXACT_SCORE')return'Risultato esatto';if(v.includes('SCORER'))return'Marcatore';if(v.startsWith('OVER_UNDER'))return'Over / Under';if(v.startsWith('HOME_GOALS')||v.startsWith('AWAY_GOALS'))return'Gol squadra';return v.replaceAll('_',' ').toLowerCase().replace(/^./,x=>x.toUpperCase())}
function marketCategory(m:Market){if(['1X2','DOUBLE_CHANCE','DRAW_NO_BET','WIN_MARGIN'].includes(m.market))return'Esito';if(m.market==='BTTS'||['MULTIGOAL','GOALS_PARITY'].includes(m.market))return'Gol';if(m.market.startsWith('OVER_UNDER'))return'Over / Under';if(m.market.startsWith('HOME_GOALS')||m.market.startsWith('AWAY_GOALS'))return'Gol squadra';if(m.market==='EXACT_SCORE')return'Risultati';if(m.market.includes('SCORER'))return'Marcatori';return'Altro'}
function shortRows(rows:Row[]):Row[]{return rows.map(r=>({...r,fixture:{...r.fixture,home:{...r.fixture.home,name:shortTeam(r.fixture.home.name)},away:{...r.fixture.away,name:shortTeam(r.fixture.away.name)}}}))}function shortTeam(name:string){const n=name.trim(),a:Record<string,string>={'FC Internazionale Milano':'Inter','Internazionale':'Inter','AC Milan':'Milan','SSC Napoli':'Napoli','AS Roma':'Roma','SS Lazio':'Lazio','ACF Fiorentina':'Fiorentina','Atalanta BC':'Atalanta','Bologna FC 1909':'Bologna','Cagliari Calcio':'Cagliari','Como 1907':'Como','Genoa CFC':'Genoa','Juventus FC':'Juventus','US Lecce':'Lecce','Parma Calcio 1913':'Parma','Torino FC':'Torino','Udinese Calcio':'Udinese','Hellas Verona FC':'Verona','US Sassuolo Calcio':'Sassuolo','US Cremonese':'Cremonese','Pisa SC':'Pisa'};return a[n]||n.replace(/\b(FC|AC|SSC|SS|AS|BC|CFC|US|Calcio|1907|1909|1913)\b/gi,'').replace(/\s+/g,' ').trim()||n}
function groupByMatchday(rows:Row[]):[string,[string,Row[]][]][]{const by=new Map<string,Row[]>();rows.forEach(r=>{const md=(r.fixture as any).matchday,key=Number.isFinite(Number(md))?`Giornata ${Number(md)}`:'Prossimo turno';by.set(key,[...(by.get(key)||[]),r])});return[...by.entries()].sort((a,b)=>Number(a[0].match(/\d+/)?.[0]||999)-Number(b[0].match(/\d+/)?.[0]||999)).map(([k,rs])=>[k,groupDates(rs)]) as any}function groupDates(rows:Row[]):[string,Row[]][]{const m=new Map<string,Row[]>();[...rows].sort((a,b)=>+new Date(a.fixture.utcDate)-+new Date(b.fixture.utcDate)).forEach(r=>{const k=day(r.fixture.utcDate);m.set(k,[...(m.get(k)||[]),r])});return[...m.entries()]}
function compactDate(v:string){return new Intl.DateTimeFormat('it-IT',{weekday:'short',day:'2-digit',month:'short'}).format(new Date(v)).replace('.','')}function time(v:string){return new Date(v).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}function matchdayDate(dates:[string,Row[]][]){const all=dates.flatMap(([,rs])=>rs).map(r=>new Date(r.fixture.utcDate)).sort((a,b)=>+a-+b);if(!all.length)return'';const fmt=(d:Date)=>new Intl.DateTimeFormat('it-IT',{day:'2-digit',month:'short'}).format(d).replace('.','');return all.length===1?fmt(all[0]):`${fmt(all[0])} – ${fmt(all[all.length-1])}`}
