'use client';
import {Dispatch,SetStateAction,useEffect,useMemo,useState} from 'react';

type Market={market:string;selection:string;probability:number;confidence:number;dataQuality:number;fairOdds?:number|null;status:'ACTIVE'|'NO_BET';reason?:string};
type Fixture={id:string;utcDate:string;status?:string;home:{id?:string;name:string};away:{id?:string;name:string}};
type Row={fixture:Fixture;markets:Market[];expectedGoalsHome?:number|null;expectedGoalsAway?:number|null};
type Pick={id:string;fixtureId:string;market:string;selection:string;eventAt:string;probability:number;confidence:number;dataQuality:number;fairOdds?:number|null;fixed?:boolean};
type Tab='Pronostici'|'Partite'|'Sistemi'|'I miei sistemi'|'Storico'|'Statistiche';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:4000';
const json=async(url:string,init?:RequestInit)=>{const r=await fetch(url,init);const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.message||`${r.status} ${r.statusText}`);return b};
const post=(url:string,body?:unknown)=>json(url,{method:'POST',headers:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});

export default function Home(){
 const [rows,setRows]=useState<Row[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[bag,setBag]=useState<Pick[]>([]),[tab,setTab]=useState<Tab>('Pronostici'),[detail,setDetail]=useState<Row|null>(null);
 const load=()=>{setLoading(true);setError('');void json(`${API}/v2/predictions?competition=SA&persist=true`).then(x=>setRows(x.data||[])).catch(e=>setError(e.message)).finally(()=>setLoading(false))};
 useEffect(()=>{load()},[]);
 const available=useMemo(()=>rows.flatMap(r=>featured(r).filter(m=>m.status==='ACTIVE').map(m=>toPick(r,m))),[rows]);
 const add=(r:Row,m:Market)=>{const p=toPick(r,m);setBag(v=>v.some(x=>x.id===p.id)?v:[...v,p])};
 return <div className="shell">
  <nav className="side" aria-label="Navigazione principale"><div className="brand">F<span>FORESIGHT</span></div>{(['Pronostici','Partite','Sistemi','I miei sistemi','Storico','Statistiche'] as Tab[]).map(x=><button key={x} className={tab===x?'on':''} onClick={()=>{setTab(x);setDetail(null)}}>{x}</button>)}</nav>
  <main><header><div><small>FOOTBALL INTELLIGENCE · DATI REALI</small><h1>{detail?'Dettaglio partita':tab}</h1></div><div className="headActions"><span className="live">● LIVE DATA</span>{detail&&<button className="ghost" onClick={()=>setDetail(null)}>← Indietro</button>}</div></header>
   {detail?<MatchDetail row={detail} bag={bag} add={add}/>:<>{tab==='Pronostici'&&<Predictions rows={rows} loading={loading} error={error} bag={bag} add={add} open={setDetail} retry={load}/>} {tab==='Partite'&&<Matches rows={rows} open={setDetail}/>} {tab==='Sistemi'&&<SystemBuilder bag={bag} setBag={setBag} available={available}/>} {tab==='I miei sistemi'&&<SavedSystems/>}{tab==='Storico'&&<History/>}{tab==='Statistiche'&&<Stats/>}</>}
  </main>
  <aside className="tray"><small>SYSTEM TRAY</small><h2>{bag.length} selezioni</h2>{bag.map(p=><div className="trayrow" key={p.id}><span><b>{p.selection}</b><small>{p.market}{p.fixed?' · FISSA':''}</small></span><button aria-label={`Rimuovi ${p.selection}`} onClick={()=>setBag(v=>v.filter(x=>x.id!==p.id))}>×</button></div>)}{!bag.length&&<p className="muted">Aggiungi un pick per costruire un sistema.</p>}<button className="primary" onClick={()=>setTab('Sistemi')}>Crea sistema</button></aside>
 </div>
}

function Predictions({rows,loading,error,bag,add,open,retry}:{rows:Row[];loading:boolean;error:string;bag:Pick[];add:(r:Row,m:Market)=>void;open:(r:Row)=>void;retry:()=>void}){
 const active=rows.flatMap(featured).filter(m=>m.status==='ACTIVE').length;
 if(loading)return <><section className="hero skeleton"><div><small>CARICAMENTO</small><h2>Analisi delle partite…</h2><p>Recupero fixture, classifiche e snapshot necessari.</p></div></section><div className="grid">{[1,2,3,4].map(x=><div className="card skeletonBox" key={x}/>)}</div></>;
 return <>{error&&<div className="notice"><b>Dati live non disponibili</b><span>{error}. Nessun valore viene sostituito con dati inventati.</span><button onClick={retry}>Riprova</button></div>}<section className="hero"><div><small>SERIE A · MODELLO VERSIONATO</small><h2>Probabilità, non certezze.</h2><p>Probability, Confidence, Data Quality e Value sono indicatori distinti. Se la qualità non basta, il risultato è NO_BET.</p></div><div className="score"><b>{active}</b><span>pick attivi</span></div></section>{!rows.length&&!error?<Empty title="Nessuna partita disponibile" text="Il provider non restituisce fixture per il periodo corrente."/>:<div className="grid">{rows.map(r=><article className="card" key={r.fixture.id}><div className="matchMeta"><small>{new Date(r.fixture.utcDate).toLocaleString('it-IT')}</small><span className="status">{r.fixture.status||'SCHEDULED'}</span></div><h3>{r.fixture.home.name} <em>—</em> {r.fixture.away.name}</h3>{featured(r).map(m=><MarketRow key={`${m.market}-${m.selection}`} row={r} market={m} added={bag.some(p=>p.id===pickId(r.fixture.id,m))} add={add}/>)}<button className="detailBtn" onClick={()=>open(r)}>Analisi completa →</button></article>)}</div>}</>;
}

function Matches({rows,open}:{rows:Row[];open:(r:Row)=>void}){return <div className="panel"><div className="sectionhead"><div><small>FIXTURE</small><h2>Partite</h2><p>Orari normalizzati e dati acquisiti dai provider gratuiti configurati.</p></div></div>{rows.length?rows.map(r=><button className="matchLine" key={r.fixture.id} onClick={()=>open(r)}><span><b>{r.fixture.home.name} — {r.fixture.away.name}</b><small>{new Date(r.fixture.utcDate).toLocaleString('it-IT')}</small></span><span>Dettaglio →</span></button>):<Empty title="Nessuna fixture" text="Avvia l’ingestion o riprova più tardi."/>}</div>}

function MatchDetail({row,bag,add}:{row:Row;bag:Pick[];add:(r:Row,m:Market)=>void}){
 const [category,setCategory]=useState('Esito'),[players,setPlayers]=useState<any[]|null>(null),[playerError,setPlayerError]=useState(''),[loadingPlayers,setLoadingPlayers]=useState(false),[value,setValue]=useState<any[]|null>(null),[valueSource,setValueSource]=useState(''),[valueReason,setValueReason]=useState(''),[loadingValue,setLoadingValue]=useState(false);
 const categories=['Esito','Gol','Team','Risultati','Combinazioni','Marcatori','Value'];
 const loadPlayers=()=>{setLoadingPlayers(true);setPlayerError('');void json(`${API}/player-markets?fixtureId=${encodeURIComponent(row.fixture.id)}&competition=SA`).then(x=>setPlayers(x.data||[])).catch(e=>setPlayerError(e.message)).finally(()=>setLoadingPlayers(false))};
 const loadValue=()=>{setLoadingValue(true);setValueReason('');void json(`${API}/v2/value?fixtureId=${encodeURIComponent(row.fixture.id)}&competition=SA`).then(x=>{setValue(x.data||[]);setValueSource(x.source||'UNAVAILABLE');setValueReason(x.reason||'')}).catch(e=>setValueReason(e.message)).finally(()=>setLoadingValue(false))};
 const select=(c:string)=>{setCategory(c);if(c==='Marcatori'&&players===null&&!loadingPlayers)loadPlayers();if(c==='Value'&&value===null&&!loadingValue)loadValue()};
 const shown=row.markets.filter(m=>marketCategory(m)===category);
 return <><section className="hero detailHero"><div><small>{new Date(row.fixture.utcDate).toLocaleString('it-IT')} · {row.fixture.status||'SCHEDULED'}</small><h2>{row.fixture.home.name} — {row.fixture.away.name}</h2><p>xG modello: {fmt(row.expectedGoalsHome)} — {fmt(row.expectedGoalsAway)}. Fair Odds derivano dal modello; Value/EV vengono mostrati solo con una quota bookmaker realmente disponibile.</p></div><div className="xg"><span>xG</span><b>{fmt(row.expectedGoalsHome)} : {fmt(row.expectedGoalsAway)}</b></div></section><div className="tabs marketTabs">{categories.map(c=><button className={category===c?'on':''} key={c} onClick={()=>select(c)}>{c}</button>)}</div><section className="panel"><div className="sectionhead"><div><small>{category.toUpperCase()}</small><h2>{category==='Marcatori'?'Probabilità giocatore':category==='Value'?'Value & quote':'Mercati e probabilità'}</h2></div></div>{category==='Marcatori'?<PlayerMarkets players={players} loading={loadingPlayers} error={playerError}/>:category==='Value'?<ValueMarkets rows={value} source={valueSource} reason={valueReason} loading={loadingValue}/>:shown.length?shown.map(m=><MarketRow key={`${m.market}-${m.selection}`} row={row} market={m} added={bag.some(p=>p.id===pickId(row.fixture.id,m))} add={add} full/>):<Empty title="Mercato non disponibile" text="Nessun mercato di questa categoria è modellabile con i dati correnti."/>}</section></>;
}

function PlayerMarkets({players,loading,error}:{players:any[]|null;loading:boolean;error:string}){if(loading)return <p className="muted">Caricamento lineup, indisponibili e marcatori…</p>;if(error)return <div className="notice"><b>Mercato non disponibile</b><span>{error}</span></div>;if(!players?.length)return <Empty title="NO_BET giocatori" text="Lineup o dati giocatore non sufficienti per una prediction affidabile."/>;return <>{players.map(p=><div className={'market '+(p.status==='NO_BET'?'off':'')} key={p.playerId}><div><small>ANYTIME SCORER</small><strong>{p.playerName}</strong><span>Conf. {pct(p.confidence)} · DQ {pct(p.dataQuality)} · {p.starterStatus||'titolarità incerta'}</span>{p.reason&&<span>{p.reason}</span>}</div><b>{pct(p.probability)}</b><span className="valueBadge">{p.status}</span></div>)}</>}

function ValueMarkets({rows,source,reason,loading}:{rows:any[]|null;source:string;reason:string;loading:boolean}){if(loading)return <p className="muted">Recupero quote pre-match on-demand…</p>;if(!rows?.length)return <Empty title="Value non disponibile" text={reason||'Nessuna quota gratuita disponibile per questa partita.'}/>;return <>{reason&&<div className="notice"><b>{source==='UNAVAILABLE'?'QUOTE NON DISPONIBILI':'INFO QUOTE'}</b><span>{reason}</span></div>}{rows.map(r=><div className="market" key={`${r.market}-${r.selection}`}><div><small>{r.market} · {r.bookmaker||'NO BOOKMAKER'}</small><strong>{r.selection}</strong><span>Fair {r.fairOdds?Number(r.fairOdds).toFixed(2):'—'} · Offerta {r.offeredOdds?Number(r.offeredOdds).toFixed(2):'—'} · EV {r.expectedValue==null?'—':pct(r.expectedValue)}</span></div><b>{pct(r.probability)}</b><span className="valueBadge">{r.valueStatus}</span></div>)}</>}

function MarketRow({row,market,added,add,full=false}:{row:Row;market:Market;added:boolean;add:(r:Row,m:Market)=>void;full?:boolean}){return <div className={'market '+(market.status==='NO_BET'?'off':'')}><div><small>{market.market}</small><strong>{market.selection}</strong><span>Confidence {pct(market.confidence)} · Data Quality {pct(market.dataQuality)}{full&&market.fairOdds?` · Fair ${market.fairOdds.toFixed(2)}`:''}</span>{market.reason&&<span>{market.reason}</span>}</div><b>{pct(market.probability)}</b><button aria-label={`Aggiungi ${market.selection}`} disabled={market.status!=='ACTIVE'||added} onClick={()=>add(row,market)}>{added?'✓':'+'}</button></div>}

function SystemBuilder({bag,setBag,available}:{bag:Pick[];setBag:Dispatch<SetStateAction<Pick[]>>;available:Pick[]}){
 const [mode,setMode]=useState<'AUTO'|'ASSISTED'|'MANUAL'>('ASSISTED'),[profile,setProfile]=useState<'PRUDENT'|'BALANCED'|'AGGRESSIVE'>('BALANCED'),[budget,setBudget]=useState(20),[minCorrect,setMinCorrect]=useState(3),[k,setK]=useState(3),[stake,setStake]=useState(1),[result,setResult]=useState<any>(),[saved,setSaved]=useState(''),[busy,setBusy]=useState(false);
 const source=mode==='AUTO'?available:bag,fixedIds=bag.filter(p=>p.fixed).map(p=>p.id);
 const toggleFixed=(id:string)=>setBag(v=>v.map(p=>p.id===id?{...p,fixed:!p.fixed}:p));
 async function build(){setBusy(true);setSaved('');try{const payload=mode==='AUTO'?{selections:source,budget,profile}:mode==='ASSISTED'?{selections:source,minCorrect,budget,profile,fixedIds}:{selections:source,k,stake,budget,fixedIds};const endpoint=mode==='AUTO'?'/systems/optimize':mode==='ASSISTED'?'/v2/systems/assist':'/v2/systems/build';setResult(await post(API+endpoint,payload))}catch(e:any){setResult({status:'ERROR',reason:e.message})}finally{setBusy(false)}}
 async function save(execution:'NOT_PLAYED'|'PLAYED'|'SIMULATED'){if(!result||result.status!=='OK')return;setBusy(true);try{const comboStake=Number(result.stake??stake),selections:Array<Pick>=result.selections||source;const savedSystem=await post(`${API}/systems/save`,{mode,profile,budget,totalCost:Number(result.cost||0),played:false,selections:selections.map(p=>({clientKey:p.id,fixtureId:p.fixtureId,market:p.market,selection:p.selection,eventAt:p.eventAt})),combinations:(result.combinations||[]).map((combo:Pick[])=>({selectionKeys:combo.map(p=>p.id),stake:comboStake}))});if(execution!=='NOT_PLAYED')await post(`${API}/v2/history/systems/${savedSystem.id}/execution`,{mode:execution});setSaved(execution==='PLAYED'?'Sistema registrato come realmente giocato.':execution==='SIMULATED'?'Sistema registrato in paper trading.':'Sistema salvato come non giocato.')}catch(e:any){setSaved(e.message)}finally{setBusy(false)}}
 return <div className="panel"><small>CREAZIONE GUIDATA</small><h2>System Builder</h2><p>Automatico seleziona opportunità valide; Assistito sviluppa i pronostici scelti; Manuale espone la combinatoria. Le incompatibilità sono sempre bloccate.</p><div className="tabs"><button className={mode==='AUTO'?'on':''} onClick={()=>setMode('AUTO')}>Automatico</button><button className={mode==='ASSISTED'?'on':''} onClick={()=>setMode('ASSISTED')}>Assistito</button><button className={mode==='MANUAL'?'on':''} onClick={()=>setMode('MANUAL')}>Manuale</button></div><div className="form"><label>Pronostici <b>{source.length}</b></label><label>Budget €<input type="number" min="1" value={budget} onChange={e=>setBudget(Number(e.target.value))}/></label><label>Profilo<select value={profile} onChange={e=>setProfile(e.target.value as any)}><option value="PRUDENT">Prudente</option><option value="BALANCED">Bilanciato</option><option value="AGGRESSIVE">Aggressivo</option></select></label>{mode==='ASSISTED'&&<label>Minimo corretti desiderato<input type="number" min="1" max={source.length||1} value={minCorrect} onChange={e=>setMinCorrect(Number(e.target.value))}/></label>}{mode==='MANUAL'&&<><label>Dimensione combinazioni<input type="number" min="1" max={source.length||1} value={k} onChange={e=>setK(Number(e.target.value))}/></label><label>Stake/combo €<input type="number" min="0.1" step="0.1" value={stake} onChange={e=>setStake(Number(e.target.value))}/></label></>}</div>{mode!=='AUTO'&&bag.length>0&&<div className="fixedList"><small>SELEZIONI · “FISSA” = PRESENTE IN OGNI COMBINAZIONE</small>{bag.map(p=><div className="fixedRow" key={p.id}><span><b>{p.selection}</b><small>{p.market}</small></span><button className={p.fixed?'fixed on':'fixed'} onClick={()=>toggleFixed(p.id)}>{p.fixed?'Fissa ✓':'Fissa'}</button></div>)}</div>}<button className="primary" disabled={busy||!source.length} onClick={build}>{busy?'Elaborazione…':'Genera sistema'}</button>{result&&<SystemResult result={result} budget={budget}/>} {result?.status==='OK'&&<div className="executionActions"><button onClick={()=>save('NOT_PLAYED')}>Salva</button><button onClick={()=>save('SIMULATED')}>Paper trading</button><button className="primary" onClick={()=>save('PLAYED')}>L’ho giocato</button></div>}{saved&&<p className="success">{saved}</p>}</div>
}

function SystemResult({result,budget}:{result:any;budget:number}){if(result.status!=='OK')return <div className="notice"><b>{result.status==='NO_BET'?'NO_BET':result.status}</b><span>{result.reason||'Il sistema non può essere generato con i vincoli correnti.'}</span></div>;return <div className="systemSummary"><div><small>COMBINAZIONI</small><b>{result.combinations?.length??0}</b></div><div><small>COSTO</small><b>€{Number(result.cost||0).toFixed(2)}</b></div><div><small>BUDGET</small><b>€{Number(budget).toFixed(2)}</b></div><div><small>RISCHIO / CORR.</small><b>{result.profile||'Custom'} {result.maxCorrelation!=null?`· ${Math.round(result.maxCorrelation*100)}%`:''}</b></div>{result.coverage&&<p><strong>Copertura:</strong> {result.coverage.explanation}<br/><span>{result.coverage.guarantee}</span></p>}</div>}

function SavedSystems(){const [items,setItems]=useState<any[]>([]),[mode,setMode]=useState('');const load=()=>json(`${API}/v2/history/systems${mode?`?mode=${mode}`:''}`).then(setItems).catch(()=>setItems([]));useEffect(()=>{void load()},[mode]);return <div className="panel"><div className="sectionhead"><div><small>PORTAFOGLIO</small><h2>I miei sistemi</h2></div><select className="compact" value={mode} onChange={e=>setMode(e.target.value)}><option value="">Tutti</option><option value="PLAYED">Reali</option><option value="SIMULATED">Paper</option><option value="NOT_PLAYED">Non giocati</option></select></div>{items.length?items.map(s=><HistoryRow key={s.id} title={`${s.mode} · ${s.selections.length} selezioni · ${s.combinations.length} combinazioni`} meta={`${executionLabel(s)} · €${Number(s.totalCost).toFixed(2)} · ${new Date(s.createdAt).toLocaleString('it-IT')}`} status={s.status}/>):<Empty title="Nessun sistema" text="I sistemi salvati appariranno qui."/>}</div>}

function History(){const [bets,setBets]=useState<any[]>([]),[mode,setMode]=useState(''),[status,setStatus]=useState(''),[market,setMarket]=useState(''),[msg,setMsg]=useState('');const load=()=>{const q=new URLSearchParams();if(mode)q.set('mode',mode);if(status)q.set('status',status);if(market)q.set('market',market);void json(`${API}/v2/history/bets?${q}`).then(setBets).catch(()=>setBets([]))};useEffect(()=>{load()},[mode,status,market]);async function settle(){const r=await post(`${API}/settlement/run`);setMsg(`${r.processed} elementi elaborati · ${r.fixturesFetched??0} fixture interrogate.`);load()}return <div className="panel"><div className="sectionhead"><div><small>AUDIT & SETTLEMENT</small><h2>Storico</h2><p>Reali, paper trading e non giocate restano sempre distinti.</p></div><button onClick={settle}>Verifica ora</button></div><div className="filters"><select value={mode} onChange={e=>setMode(e.target.value)}><option value="">Tutte</option><option value="PLAYED">Reali</option><option value="SIMULATED">Paper</option><option value="NOT_PLAYED">Non giocate</option></select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Ogni esito</option><option>WIN</option><option>LOSS</option><option>VOID</option><option>PENDING</option></select><input placeholder="Mercato (es. 1X2)" value={market} onChange={e=>setMarket(e.target.value)}/></div>{msg&&<p className="success">{msg}</p>}{bets.length?bets.map(b=><HistoryRow key={b.id} title={`${b.selection} · ${b.market}`} meta={`${executionLabel(b)}${b.bookmaker?` · ${b.bookmaker}`:''}${b.odds?` · @${b.odds}`:''} · stake €${Number(b.stake).toFixed(2)}`} status={b.status}/>):<Empty title="Nessuna giocata" text="I record che rispettano i filtri appariranno qui."/>}</div>}

function Stats(){const [m,setM]=useState<any>(),[error,setError]=useState('');useEffect(()=>{void json(`${API}/ops/performance`).then(setM).catch(e=>setError(e.message))},[]);if(error)return <div className="notice"><b>Analytics non disponibili</b><span>{error}</span></div>;return <><div className="stats"><article><small>MODEL PERFORMANCE</small><b>{m?.modelPerformance?.sample??0} sample</b><span>Brier {num(m?.modelPerformance?.brierScore,3)} · Hit {pct(m?.modelPerformance?.hitRate)}</span></article><article><small>BETTING PERFORMANCE · SOLO REALI</small><b>{m?.bettingPerformance?.profit==null?'—':`€${m.bettingPerformance.profit.toFixed(2)}`}</b><span>ROI {pct(m?.bettingPerformance?.roi)} · Win {pct(m?.bettingPerformance?.winRate)}</span></article><article><small>MAX DRAWDOWN</small><b>{m?.bettingPerformance?.maxDrawdown==null?'—':`€${m.bettingPerformance.maxDrawdown.toFixed(2)}`}</b><span>Quota media {num(m?.bettingPerformance?.averageOdds,2)}</span></article></div><section className="panel"><small>CALIBRAZIONE</small><h2>Probabilità dichiarata vs osservata</h2><div className="calibration">{(m?.modelPerformance?.calibration||[]).map((b:any)=><div key={b.range}><span>{b.range}</span><progress max="1" value={b.observed??0}/><small>{b.sample} · obs {pct(b.observed)}</small></div>)}</div></section></>}

function HistoryRow({title,meta,status}:{title:string;meta:string;status:string}){return <div className="history"><span><b>{title}</b><small>{meta}</small></span><strong className={`status status-${String(status).toLowerCase()}`}>{status}</strong></div>}
function Empty({title,text}:{title:string;text:string}){return <div className="empty"><b>{title}</b><span>{text}</span></div>}
function featured(row:Row){const choose=(f:(m:Market)=>boolean)=>row.markets.filter(f).sort((a,b)=>b.probability-a.probability)[0];return [choose(m=>m.market==='1X2'),choose(m=>m.market==='OVER_UNDER_2_5'),choose(m=>m.market==='BTTS'),choose(m=>m.market.startsWith('HOME_GOALS_1_5')||m.market.startsWith('AWAY_GOALS_1_5'))].filter(Boolean) as Market[]}
function marketCategory(m:Market){if(['1X2','DOUBLE_CHANCE','DRAW_NO_BET'].includes(m.market))return 'Esito';if(m.market.startsWith('OVER_UNDER')||m.market==='BTTS'||m.market==='MULTIGOAL')return 'Gol';if(m.market.startsWith('HOME_GOALS')||m.market.startsWith('AWAY_GOALS'))return 'Team';if(m.market==='EXACT_SCORE')return 'Risultati';if(m.market==='COMBO')return 'Combinazioni';return 'Altro'}
function pickId(fixtureId:string,m:Market){return `${fixtureId}|${m.market}|${m.selection}`}
function toPick(row:Row,m:Market):Pick{return {id:pickId(row.fixture.id,m),fixtureId:row.fixture.id,market:m.market,selection:m.selection,eventAt:row.fixture.utcDate,probability:m.probability,confidence:m.confidence,dataQuality:m.dataQuality,fairOdds:m.fairOdds}}
function pct(v:any){return v==null?'—':`${Math.round(Number(v)*100)}%`}
function num(v:any,d=2){return v==null?'—':Number(v).toFixed(d)}
function fmt(v:any){return v==null?'—':Number(v).toFixed(2)}
function executionLabel(x:any){return x.played?'REALE':x.simulated?'PAPER':'NON GIOCATO'}
