'use client';
import {useEffect,useMemo,useState} from 'react';

type Market={market:string;selection:string;probability:number;confidence:number;dataQuality:number;status:string;reason?:string};
type Fixture={id:string;utcDate:string;home:{name:string};away:{name:string}};
type Row={fixture:Fixture;markets:Market[]};
type Pick={id:string;fixtureId:string;market:string;selection:string;eventAt:string;probability:number;confidence:number;dataQuality:number};
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:4000';
const json=(url:string,init?:RequestInit)=>fetch(url,init).then(async r=>{if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json()});

export default function Home(){
 const [rows,setRows]=useState<Row[]>([]),[error,setError]=useState(''),[bag,setBag]=useState<Pick[]>([]),[tab,setTab]=useState('Pronostici');
 useEffect(()=>{json(API+'/predictions?competition=SA&persist=true').then(x=>setRows(x.data||[])).catch(e=>setError(e.message))},[]);
 const active=useMemo(()=>rows.flatMap(r=>r.markets.filter(m=>m.status==='ACTIVE').map(m=>({r,m}))),[rows]);
 const add=(r:Row,m:Market)=>setBag(v=>v.some(p=>p.id===r.fixture.id+m.market)?v:[...v,{id:r.fixture.id+m.market,fixtureId:r.fixture.id,market:m.market,selection:m.selection,eventAt:r.fixture.utcDate,probability:m.probability,confidence:m.confidence,dataQuality:m.dataQuality}]);
 return <div className="shell">
  <aside className="side"><div className="brand">F<span>FORESIGHT</span></div>{['Pronostici','Partite','Sistemi','Storico','Statistiche'].map(x=><button key={x} className={tab===x?'on':''} onClick={()=>setTab(x)}>{x}</button>)}</aside>
  <main><header><div><small>FOOTBALL INTELLIGENCE</small><h1>{tab}</h1></div><span className="live">● LIVE DATA</span></header>
   {tab==='Pronostici'&&<>{error&&<div className="notice"><b>Dati live non disponibili.</b><span>{error}. Nessun dato viene sostituito con valori inventati.</span></div>}<section className="hero"><div><small>SERIE A · POISSON BOOTSTRAP v1</small><h2>Probabilità, non certezze.</h2><p>Probability, Confidence e Data Quality sono indicatori distinti. NO_BET è un risultato valido.</p></div><div className="score"><b>{active.length}</b><span>pick attivi</span></div></section><div className="grid">{rows.map(r=><article className="card" key={r.fixture.id}><small>{new Date(r.fixture.utcDate).toLocaleString('it-IT')}</small><h3>{r.fixture.home.name} <em>—</em> {r.fixture.away.name}</h3>{r.markets.map(m=><div className={'market '+(m.status==='NO_BET'?'off':'')} key={m.market}><div><small>{m.market}</small><strong>{m.selection}</strong><span>Conf. {Math.round(m.confidence*100)}% · DQ {Math.round(m.dataQuality*100)}%</span>{m.reason&&<span>{m.reason}</span>}</div><b>{Math.round(m.probability*100)}%</b><button aria-label={`Aggiungi ${m.selection}`} disabled={m.status!=='ACTIVE'||bag.some(p=>p.id===r.fixture.id+m.market)} onClick={()=>add(r,m)}>+</button></div>)}</article>)}</div></>}
   {tab==='Sistemi'&&<System bag={bag}/>} {tab==='Storico'&&<History/>}{tab==='Statistiche'&&<Stats/>}{tab==='Partite'&&<div className="panel"><h2>Partite</h2><p>Fixture caricate automaticamente dal provider gratuito configurato.</p>{rows.map(r=><p key={r.fixture.id}><b>{r.fixture.home.name} — {r.fixture.away.name}</b> · {new Date(r.fixture.utcDate).toLocaleString('it-IT')}</p>)}</div>}
  </main>
  <aside className="tray"><small>SYSTEM TRAY</small><h2>{bag.length} selezioni</h2>{bag.map(p=><div className="trayrow" key={p.id}><span><b>{p.selection}</b><small>{p.market}</small></span><button aria-label="Rimuovi" onClick={()=>setBag(v=>v.filter(x=>x.id!==p.id))}>×</button></div>)}{!bag.length&&<p className="muted">Aggiungi un pick compatibile per iniziare.</p>}<button className="primary" onClick={()=>setTab('Sistemi')}>Crea sistema</button></aside>
 </div>
}

function System({bag}:{bag:Pick[]}){
 const [mode,setMode]=useState<'AUTO'|'MANUAL'>('AUTO'),[profile,setProfile]=useState<'PRUDENT'|'BALANCED'|'AGGRESSIVE'>('BALANCED'),[budget,setBudget]=useState(20),[k,setK]=useState(3),[stake,setStake]=useState(1),[result,setResult]=useState<any>(),[saved,setSaved]=useState('');
 async function build(){setSaved('');const body=mode==='AUTO'?{selections:bag,budget,profile}:{selections:bag,k,stake,budget};setResult(await json(API+(mode==='AUTO'?'/systems/optimize':'/systems/build'),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}))}
 async function save(played:boolean){
  if(!result||result.status!=='OK')return;
  const totalCost=Number(result.cost||0),comboStake=Number(result.stake??stake);
  const payload={mode,profile,budget,totalCost,played,selections:bag.map(p=>({clientKey:p.id,fixtureId:p.fixtureId,market:p.market,selection:p.selection,eventAt:p.eventAt})),combinations:(result.combinations||[]).map((combo:Pick[])=>({selectionKeys:combo.map(p=>p.id),stake:comboStake}))};
  await json(API+'/systems/save',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});
  setSaved(played?'Sistema registrato come realmente giocato.':'Sistema salvato come non giocato.');
 }
 return <div className="panel"><small>CREAZIONE GUIDATA</small><h2>System Optimizer</h2><div className="tabs"><button className={mode==='AUTO'?'on':''} onClick={()=>setMode('AUTO')}>Automatico</button><button className={mode==='MANUAL'?'on':''} onClick={()=>setMode('MANUAL')}>Manuale</button></div><div className="form"><label>Pronostici <b>{bag.length}</b></label><label>Budget €<input type="number" min="1" value={budget} onChange={e=>setBudget(Number(e.target.value))}/></label>{mode==='AUTO'?<label>Profilo<select value={profile} onChange={e=>setProfile(e.target.value as any)}><option value="PRUDENT">Prudente</option><option value="BALANCED">Bilanciato</option><option value="AGGRESSIVE">Aggressivo</option></select></label>:<><label>Combinazioni k<input type="number" min="1" max={bag.length||1} value={k} onChange={e=>setK(Number(e.target.value))}/></label><label>Stake/combo €<input type="number" min="0.1" step="0.1" value={stake} onChange={e=>setStake(Number(e.target.value))}/></label></>}</div><button className="primary" disabled={!bag.length||(mode==='MANUAL'&&k>bag.length)} onClick={build}>Genera sistema</button>{result&&<div className={result.status==='OK'?'success':'notice'}><b>{result.status==='OK'?`${result.combinations.length} combinazioni · costo €${Number(result.cost).toFixed(2)}`:result.status==='NO_BET'?'NO_BET':`INCOMPATIBLE`}</b><span>{result.reason||''}{result.withinBudget===false?' Budget superato.':''}</span></div>}{result?.status==='OK'&&<div className="actions"><button onClick={()=>save(false)}>Salva</button><button className="primary" onClick={()=>save(true)}>L’ho giocato</button></div>}{saved&&<p className="success">{saved}</p>}</div>
}

function History(){
 const [bets,setBets]=useState<any[]>([]),[systems,setSystems]=useState<any[]>([]),[msg,setMsg]=useState('');const load=()=>Promise.all([json(API+'/bets').catch(()=>[]),json(API+'/systems').catch(()=>[])]).then(([b,s])=>{setBets(b);setSystems(s)});useEffect(()=>{load()},[]);async function settle(){const r=await json(API+'/settlement/run',{method:'POST'});setMsg(`${r.processed} elementi verificati/elaborati.`);await load()}
 return <div className="panel"><div className="sectionhead"><div><h2>Storico</h2><p>Prediction, paper/non giocate e scommesse reali sono mantenute separate.</p></div><button onClick={settle}>Verifica ora</button></div>{msg&&<p className="success">{msg}</p>}<h3>Sistemi</h3>{systems.length?systems.map(s=><div className="history" key={s.id}><span><b>{s.mode} · {s.selections.length} selezioni · {s.combinations?.length??0} combinazioni</b><small>{s.played?'REALE':'NON GIOCATO'} · {new Date(s.createdAt).toLocaleString('it-IT')}</small></span><strong>{s.status}</strong></div>):<p className="muted">Nessun sistema salvato.</p>}<h3>Singole</h3>{bets.length?bets.map(b=><div className="history" key={b.id}><span><b>{b.selection}</b><small>{b.played?'REALE':'NON GIOCATA'} · {b.market}</small></span><strong>{b.status}</strong></div>):<p className="muted">Nessuna singola registrata.</p>}</div>
}

function Stats(){const [m,setM]=useState<any>();useEffect(()=>{json(API+'/metrics').then(setM).catch(()=>setM(null))},[]);const pct=(v:any)=>v==null?'—':`${(v*100).toFixed(1)}%`;return <div className="stats"><article><small>MODEL PERFORMANCE</small><b>{m?.modelPerformance?.sample??0} sample</b><span>Brier {m?.modelPerformance?.brierScore==null?'—':m.modelPerformance.brierScore.toFixed(3)} · Hit {pct(m?.modelPerformance?.hitRate)}</span></article><article><small>BETTING PERFORMANCE</small><b>{m?.bettingPerformance?.profit==null?'—':`€${m.bettingPerformance.profit.toFixed(2)}`}</b><span>ROI {pct(m?.bettingPerformance?.roi)} · stake €{m?.bettingPerformance?.stake?.toFixed?.(2)??'0.00'}</span></article><article><small>NO BET</small><b>Risultato valido</b><span>Il motore non forza selezioni quando dati/confidence sono insufficienti.</span></article></div>}
