'use client';
import {Dispatch,SetStateAction,useEffect,useState} from 'react';

export type SystemPick={id:string;fixtureId:string;market:string;selection:string;eventAt:string;probability:number;confidence:number;dataQuality:number;fairOdds?:number|null;fixed?:boolean;period?:'FT'|'HT';metric?:string;operator?:string;threshold?:number;outcome?:string;teamSide?:'HOME'|'AWAY';playerId?:string;homeName?:string;awayName?:string};
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:4000';
const json=async(url:string,init?:RequestInit)=>{const response=await fetch(url,init);const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body?.message||`${response.status} ${response.statusText}`);return body};
const post=(url:string,body?:unknown)=>json(url,{method:'POST',headers:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});

export default function SystemBuilderPanel({bag,setBag,available}:{bag:SystemPick[];setBag:Dispatch<SetStateAction<SystemPick[]>>;available:SystemPick[]}){
 const[mode,setMode]=useState<'AUTO'|'ASSISTED'|'MANUAL'>('ASSISTED'),[profile,setProfile]=useState<'PRUDENT'|'BALANCED'|'AGGRESSIVE'>('BALANCED');
 const[budget,setBudget]=useState(20),[minCorrect,setMinCorrect]=useState(3),[k,setK]=useState(3),[stake,setStake]=useState(1),[result,setResult]=useState<any>(),[saved,setSaved]=useState(''),[busy,setBusy]=useState(false),[bookmaker,setBookmaker]=useState(''),[analysis,setAnalysis]=useState<any>(),[actualOdds,setActualOdds]=useState<Record<string,string>>({});
 const source=mode==='AUTO'?available:bag,fixedIds=bag.filter(p=>p.fixed).map(p=>p.id),resultSelections:SystemPick[]=result?.selections||source;
 const toggleFixed=(id:string)=>setBag(items=>items.map(p=>p.id===id?{...p,fixed:!p.fixed}:p));
 const removePick=(id:string)=>{setBag(items=>items.filter(p=>p.id!==id));setResult(undefined);setSaved('')};
 useEffect(()=>{let active=true;if(mode==='AUTO'||bag.length<2){setAnalysis(undefined);return()=>{active=false}};post(`${API}/v2/systems/analyze`,{selections:bag}).then(value=>{if(active)setAnalysis(value)}).catch(error=>{if(active)setAnalysis({status:'ERROR',reason:error.message})});return()=>{active=false}},[bag,mode]);
 async function build(){setBusy(true);setSaved('');try{const payload=mode==='AUTO'?{selections:source,budget,profile}:mode==='ASSISTED'?{selections:source,minCorrect,budget,profile,fixedIds}:{selections:source,k,stake,budget,fixedIds};const endpoint=mode==='AUTO'?'/v2/systems/optimize':mode==='ASSISTED'?'/v2/systems/assist':'/v2/systems/build';setResult(await post(API+endpoint,payload))}catch(e:any){setResult({status:'ERROR',reason:e.message})}finally{setBusy(false)}}
 async function save(execution:'NOT_PLAYED'|'PLAYED'|'SIMULATED'){if(!result||result.status!=='OK')return;const oddsById=new Map<string,number>();if(execution!=='NOT_PLAYED'){for(const p of resultSelections){const odds=Number(actualOdds[p.id]);if(!Number.isFinite(odds)||odds<=1){setSaved(`Inserisci la quota disponibile per ${friendlyPick(p)}.`);return}oddsById.set(p.id,odds)}}setBusy(true);setSaved('');try{const comboStake=Number(result.stake??stake);const savedSystem=await post(`${API}/systems/save`,{mode,profile,budget,totalCost:Number(result.cost||0),played:false,selections:resultSelections.map(p=>({clientKey:p.id,fixtureId:p.fixtureId,market:p.market,selection:p.selection,eventAt:p.eventAt,odds:execution!=='NOT_PLAYED'?oddsById.get(p.id):undefined})),combinations:(result.combinations||[]).map((combo:SystemPick[])=>({selectionKeys:combo.map(p=>p.id),stake:comboStake}))});if(execution!=='NOT_PLAYED')await post(`${API}/v2/history/systems/${savedSystem.id}/execution`,{mode:execution,bookmaker:bookmaker.trim()||undefined});setSaved(execution==='PLAYED'?'Sistema registrato come giocato.':execution==='SIMULATED'?'Sistema registrato come simulazione.':'Sistema salvato.')}catch(e:any){setSaved(e.message)}finally{setBusy(false)}}
 const blocked=mode!=='AUTO'&&analysis?.status==='INCOMPATIBLE';
 return <div className="panel systemFriendly"><div className="systemTitle"><div><small>SCHEDINA / SISTEMA</small><h2>Crea il tuo sistema</h2></div><span>{source.length} {source.length===1?'selezione':'selezioni'}</span></div><div className="tabs systemModeTabs"><button className={mode==='AUTO'?'on':''} onClick={()=>setMode('AUTO')}>Crea per me</button><button className={mode==='ASSISTED'?'on':''} onClick={()=>setMode('ASSISTED')}>Con le mie scelte</button><button className={mode==='MANUAL'?'on':''} onClick={()=>setMode('MANUAL')}>Avanzato</button></div>
 <div className="form systemControls"><label>Budget €<input aria-label="Budget sistema" type="number" min="1" value={budget} onChange={e=>setBudget(Number(e.target.value))}/></label><label>Profilo<select aria-label="Livello di rischio" value={profile} onChange={e=>setProfile(e.target.value as any)}><option value="PRUDENT">Prudente</option><option value="BALANCED">Bilanciato</option><option value="AGGRESSIVE">Aggressivo</option></select></label></div>
 {mode==='ASSISTED'&&source.length>0&&<details className="executionDetails"><summary>Copertura del sistema</summary><label>Quante selezioni vuoi provare a coprire?<input type="number" min="1" max={source.length||1} value={minCorrect} onChange={e=>setMinCorrect(Number(e.target.value))}/></label></details>}
 {mode==='MANUAL'&&<details className="executionDetails" open><summary>Configurazione avanzata</summary><div className="form"><label>Selezioni per combinazione<input type="number" min="1" max={source.length||1} value={k} onChange={e=>setK(Number(e.target.value))}/></label><label>Importo per combinazione €<input type="number" min="0.1" step="0.1" value={stake} onChange={e=>setStake(Number(e.target.value))}/></label></div></details>}
 {mode!=='AUTO'&&bag.length>0&&<div className="fixedList systemPickList"><div className="systemListHead"><small>LE TUE SELEZIONI</small><span>Tocca × per rimuovere</span></div>{bag.map((p,i)=><div className={`fixedRow systemPickRow ${i%2?'even':'odd'}`} key={p.id}><div className="systemPickMain"><small>{formatDate(p.eventAt)}</small><b>{friendlyPick(p)}</b><span>{friendlyMarket(p.market)}</span></div><div className="systemPickActions"><button className={p.fixed?'fixed on':'fixed'} onClick={()=>toggleFixed(p.id)}>{p.fixed?'Fissa ✓':'Rendi fissa'}</button><button className="removePick" aria-label={`Rimuovi ${friendlyPick(p)}`} onClick={()=>removePick(p.id)}>×</button></div></div>)}</div>}
 {analysis?.status==='INCOMPATIBLE'&&<div className="notice"><b>Queste scelte non possono stare insieme</b><span>{analysis.reason}</span></div>}
 {analysis?.status==='OK'&&analysis.correlations?.length>0&&<div className="notice"><b>Alcune scelte sono collegate</b><span>FPS ne terrà conto quando costruisce le combinazioni.</span></div>}
 <button className="primary systemPrimary" disabled={busy||!source.length||blocked} onClick={build}>{busy?'Sto creando il sistema…':blocked?'Modifica le scelte incompatibili':'Crea sistema'}</button>
 {result&&<SystemResult result={result} budget={budget} fallbackStake={stake}/>} 
 {result?.status==='OK'&&<details className="executionDetails"><summary>Registrazione e quote</summary><div className="form"><label>Bookmaker (opzionale)<input value={bookmaker} onChange={e=>setBookmaker(e.target.value)} placeholder="Bookmaker"/></label>{resultSelections.map(p=><label key={p.id}>Quota · {friendlyPick(p)}<input aria-label={`Quota effettiva ${friendlyPick(p)}`} type="number" min="1.01" step="0.01" value={actualOdds[p.id]||''} onChange={e=>setActualOdds(v=>({...v,[p.id]:e.target.value}))} placeholder="es. 1.85"/></label>)}</div></details>}
 {result?.status==='OK'&&<div className="executionActions"><button onClick={()=>save('NOT_PLAYED')}>Salva</button><button onClick={()=>save('SIMULATED')}>Simula</button><button className="primary" onClick={()=>save('PLAYED')}>L’ho giocato</button></div>}
 {saved&&<p className={saved.startsWith('Sistema registrato')||saved.startsWith('Sistema salvato')?'success':'notice'}>{saved}</p>}</div>
}

function friendlyPick(p:SystemPick){const s=String(p.selection||'').toUpperCase();if(p.market==='1X2'){if(s==='1'||s==='HOME')return p.homeName?`Vince ${p.homeName}`:'Vince la squadra di casa';if(s==='2'||s==='AWAY')return p.awayName?`Vince ${p.awayName}`:'Vince la squadra ospite';if(s==='X'||s==='DRAW')return'Pareggio'}if(s==='HOME')return p.homeName||'Squadra di casa';if(s==='AWAY')return p.awayName||'Squadra ospite';if(p.market==='BTTS')return s==='GOAL'?'Entrambe segnano':'Almeno una non segna';if(p.market==='EXACT_SCORE')return`Risultato esatto ${p.selection}`;return String(p.selection).replaceAll('_',' ').replace(/\bHOME\b/g,p.homeName||'Casa').replace(/\bAWAY\b/g,p.awayName||'Ospite').replace(/OVER/g,'Over').replace(/UNDER/g,'Under')}
function friendlyMarket(v:string){return v==='1X2'?'Esito finale':v==='BTTS'?'Gol / No Gol':v==='EXACT_SCORE'?'Risultato esatto':v.replaceAll('_',' ').replace(/HOME/g,'Casa').replace(/AWAY/g,'Ospite').toLowerCase()}
function formatDate(v:string){return new Date(v).toLocaleDateString('it-IT',{weekday:'short',day:'2-digit',month:'short'}).replace('.','')}
function SystemResult({result,budget,fallbackStake}:{result:any;budget:number;fallbackStake:number}){if(result.status!=='OK')return <div className="notice"><b>{result.status==='NO_BET'?'Nessun sistema consigliato':'Impossibile creare il sistema'}</b><span>{result.reason||'Prova a modificare le scelte o il budget.'}</span></div>;const comboStake=Number(result.stake??fallbackStake);return <div className="systemSummary"><div><small>Combinazioni</small><b>{result.combinations?.length??0}</b></div><div><small>Per combinazione</small><b>€{comboStake.toFixed(2)}</b></div><div><small>Costo totale</small><b>€{Number(result.cost||0).toFixed(2)}</b></div><div><small>Budget</small><b>€{Number(budget).toFixed(2)}</b></div><div><small>Profilo</small><b>{result.profile==='PRUDENT'?'Prudente':result.profile==='AGGRESSIVE'?'Aggressivo':result.profile==='BALANCED'?'Bilanciato':'Personalizzato'}</b></div>{result.coverage&&<p><strong>Copertura:</strong> {result.coverage.explanation}<br/><span>{result.coverage.guarantee}</span></p>}</div>}
