import {Body,Controller,Get,Post,Query} from '@nestjs/common';import {buildSystem,optimizeSystem,predictMarkets,settlementEligible,Selection} from '@fps/domain';import {FootballProvider,PrismaService} from './services';import {SettlementService} from './settlement.service';
@Controller() export class AppController{constructor(private football:FootballProvider,private db:PrismaService,private settlement:SettlementService){}
@Get('health')health(){return {status:'ok',service:'fps-api',time:new Date().toISOString()}}
@Get('fixtures')async fixtures(@Query('competition')c='SA',@Query('date')d?:string){return {source:'football-data.org',data:await this.football.fixtures(c,d)}}
@Get('predictions')async predictions(@Query('competition')c='SA',@Query('date')d?:string,@Query('persist')persist='false'){const [fx,st]=await Promise.all([this.football.fixtures(c,d),this.football.standings(c)]);const map=new Map(st.map(x=>[x.teamId,x]));const data=fx.map(f=>{const h=map.get(f.home.id),a=map.get(f.away.id);const markets=h&&a?predictMarkets(h,a):[{market:'MODEL',selection:'NO_BET',probability:0,confidence:0,dataQuality:0,status:'NO_BET' as const,reason:'Statistiche mancanti'}];return {fixture:f,markets}});if(persist==='true'){for(const row of data){await this.db.predictionRun.create({data:{fixtureId:row.fixture.id,modelVersion:'poisson-bootstrap-v1',source:'football-data.org',eventAt:new Date(row.fixture.utcDate),snapshots:{create:row.markets.map(m=>({market:m.market,selection:m.selection,probability:m.probability,confidence:m.confidence,dataQuality:m.dataQuality,status:m.status}))}}})}}return {source:'football-data.org',modelVersion:'poisson-bootstrap-v1',data}}
@Post('systems/build')systems(@Body()b:{selections:Selection[];k:number;stake:number;budget?:number}){const r=buildSystem(b.selections,b.k,b.stake);return {...r,budget:b.budget??null,withinBudget:b.budget==null||r.cost<=b.budget}}
@Post('systems/optimize')optimize(@Body()b:{selections:Selection[];budget:number;profile?:'PRUDENT'|'BALANCED'|'AGGRESSIVE'}){return optimizeSystem(b.selections,b.budget,b.profile||'BALANCED')}
@Post('systems/save')async saveSystem(@Body()b:{mode:string;profile?:string;budget:number;totalCost:number;played:boolean;selections:Array<{fixtureId:string;market:string;selection:string;eventAt:string;odds?:number}>}){const system=await this.db.bettingSystem.create({data:{mode:b.mode,profile:b.profile,budget:b.budget,totalCost:b.totalCost,played:b.played,selections:{create:b.selections.map(s=>({...s,eventAt:new Date(s.eventAt)}))}},include:{selections:true}});await this.db.auditEvent.create({data:{entityType:'BettingSystem',entityId:system.id,action:b.played?'REAL_SYSTEM_RECORDED':'SYSTEM_SAVED'}});return system}
@Get('systems')async savedSystems(){return this.db.bettingSystem.findMany({include:{selections:true},orderBy:{createdAt:'desc'}})}
@Post('bets')async createBet(@Body()b:{fixtureId:string;market:string;selection:string;stake:number;odds?:number;played:boolean;eventAt:string}){const bet=await this.db.bet.create({data:{...b,eventAt:new Date(b.eventAt)}});await this.db.auditEvent.create({data:{entityType:'Bet',entityId:bet.id,action:b.played?'REAL_BET_RECORDED':'PREDICTION_SAVED'}});return bet}
@Get('bets')async bets(@Query('played')p?:string){return this.db.bet.findMany({where:p===undefined?{}:{played:p==='true'},orderBy:{createdAt:'desc'}})}
@Get('metrics')async metrics(){const snaps=await this.db.predictionSnapshot.findMany({where:{outcome:{in:['WIN','LOSS']}}});const brier=snaps.length?snaps.reduce((s,p)=>s+Math.pow(p.probability-(p.outcome==='WIN'?1:0),2),0)/snaps.length:null;const hit=snaps.length?snaps.filter(p=>p.outcome==='WIN').length/snaps.length:null;const real=await this.db.bet.findMany({where:{played:true,status:{in:['WIN','LOSS']}}});const stake=real.reduce((s,b)=>s+b.stake,0);const returns=real.reduce((s,b)=>s+(b.status==='WIN'?b.stake*(b.odds??1):0),0);const systems=await this.db.bettingSystem.groupBy({by:['status'],where:{played:true},_count:{_all:true}});return {modelPerformance:{sample:snaps.length,brierScore:brier,hitRate:hit},bettingPerformance:{sample:real.length,stake,returns,profit:returns-stake,roi:stake?((returns-stake)/stake):null},systemPerformance:systems}}
@Post('settlement/eligible')async eligible(){const pending=await this.db.bet.findMany({where:{played:true,status:'PENDING'}});return pending.filter(b=>settlementEligible(b.eventAt,!!b.verifiedAt)).map(b=>({id:b.id,fixtureId:b.fixtureId,eventAt:b.eventAt}))}
@Post('settlement/run')async settle(){return this.settlement.run()}
}
