import {Injectable,Logger} from '@nestjs/common';import {Cron} from '@nestjs/schedule';import {settleMarket,settlementEligible} from '@fps/domain';import {FootballProvider,PrismaService} from './services';
@Injectable() export class SettlementService{
 private readonly log=new Logger(SettlementService.name);private running=false;constructor(private football:FootballProvider,private db:PrismaService){}
 @Cron('0 */10 * * * *') async scheduled(){if(this.running)return;this.running=true;try{await this.run()}catch(e){this.log.error(e)}finally{this.running=false}}
 private async verifiedResult(fixtureId:string){const result=await this.football.result(fixtureId);if(result.status!=='FINISHED'||result.home==null||result.away==null)return null;return {...result,version:`fd:${fixtureId}:${result.lastUpdated||'v1'}`};}
 async run(){const results:any[]=[];await this.settleBets(results);await this.settleSystems(results);await this.settlePredictions(results);return {processed:results.length,results}}
 private async settleBets(out:any[]){const pending=await this.db.bet.findMany({where:{played:true,status:'PENDING',verifiedAt:null}});for(const bet of pending.filter(b=>settlementEligible(b.eventAt,false))){const result=await this.verifiedResult(bet.fixtureId);if(!result){out.push({type:'BET',id:bet.id,status:'WAITING'});continue}const decision=settleMarket(bet.market,bet.selection,{home:result.home!,away:result.away!});if(decision==='UNSUPPORTED'){out.push({type:'BET',id:bet.id,status:'UNSUPPORTED'});continue}const updated=await this.db.bet.updateMany({where:{id:bet.id,status:'PENDING',verifiedAt:null},data:{status:decision,verifiedAt:new Date(),resultVersion:result.version}});if(updated.count===1){await this.audit('Bet',bet.id,decision,result);out.push({type:'BET',id:bet.id,status:decision})}}
 }
 private async settleSystems(out:any[]){const selections=await this.db.systemSelection.findMany({where:{status:'PENDING',verifiedAt:null,system:{played:true}},include:{system:true}});for(const pick of selections.filter(s=>settlementEligible(s.eventAt,false))){const result=await this.verifiedResult(pick.fixtureId);if(!result){out.push({type:'SYSTEM_SELECTION',id:pick.id,status:'WAITING'});continue}const decision=settleMarket(pick.market,pick.selection,{home:result.home!,away:result.away!});if(decision==='UNSUPPORTED'){out.push({type:'SYSTEM_SELECTION',id:pick.id,status:'UNSUPPORTED'});continue}const updated=await this.db.systemSelection.updateMany({where:{id:pick.id,status:'PENDING',verifiedAt:null},data:{status:decision,verifiedAt:new Date(),resultVersion:result.version}});if(updated.count===1){await this.audit('SystemSelection',pick.id,decision,result);out.push({type:'SYSTEM_SELECTION',id:pick.id,status:decision})}}const systems=await this.db.bettingSystem.findMany({where:{played:true,status:'PENDING'},include:{selections:true}});for(const s of systems){if(s.selections.length&&s.selections.every(x=>x.status!=='PENDING')){const status=s.selections.some(x=>x.status==='LOSS')?'LOSS':s.selections.every(x=>x.status==='WIN')?'WIN':'PARTIAL';await this.db.bettingSystem.updateMany({where:{id:s.id,status:'PENDING'},data:{status}});out.push({type:'SYSTEM',id:s.id,status})}}
 }
 private async settlePredictions(out:any[]){const runs=await this.db.predictionRun.findMany({where:{eventAt:{lte:new Date(Date.now()-150*60000)},snapshots:{some:{outcome:null}}},include:{snapshots:true}});for(const run of runs){const result=await this.verifiedResult(run.fixtureId);if(!result)continue;for(const p of run.snapshots.filter(x=>x.outcome===null)){if(p.status==='NO_BET'){await this.db.predictionSnapshot.updateMany({where:{id:p.id,outcome:null},data:{outcome:'NO_BET',settledAt:new Date(),resultVersion:result.version}});continue}const decision=settleMarket(p.market,p.selection,{home:result.home!,away:result.away!});if(decision==='UNSUPPORTED')continue;await this.db.predictionSnapshot.updateMany({where:{id:p.id,outcome:null},data:{outcome:decision,settledAt:new Date(),resultVersion:result.version}});out.push({type:'PREDICTION',id:p.id,status:decision})}}
 }
 private async audit(entityType:string,entityId:string,decision:string,result:any){await this.db.auditEvent.create({data:{entityType,entityId,action:'SETTLED',payload:{decision,score:{home:result.home,away:result.away},resultVersion:result.version}}})}
}
