import { DEFAULT_MODEL_CONFIG, MODEL_CONFIG_VERSION, MODEL_VERSION, predictFixture, type MatchContext, type VenueMetrics } from '@fps/domain';

export type Fixture={id:string;utcDate:string;status:string;home:{id:string;name:string};away:{id:string;name:string}};
export type Standing={teamId:string;played:number;points:number;goalsFor:number;goalsAgainst:number;formIndex?:number;home?:VenueMetrics;away?:VenueMetrics};
export type ProviderCredentials={footballDataToken:string;apiFootballKey?:string};
export type PredictionRow={fixture:Fixture;expectedGoalsHome:number|null;expectedGoalsAway:number|null;markets:any[];inputs:any};

export interface SecretStore{get(key:string):Promise<string|null>;set(key:string,value:string):Promise<void>;remove(key:string):Promise<void>}
export interface LocalStore{init():Promise<void>;savePredictionRun(run:any):Promise<void>;listPredictionRuns(filters?:Record<string,unknown>):Promise<any[]>;saveRecord(kind:string,record:any):Promise<void>;listRecords(kind:string,filters?:Record<string,unknown>):Promise<any[]>}

export class FootballProvider{
  constructor(private credentials:ProviderCredentials,private fd='https://api.football-data.org/v4',private af='https://v3.football.api-sports.io'){}
  private async request(url:string,headers:Record<string,string>){const r=await fetch(url,{headers});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json() as Promise<any>}
  async fixtures(competition='SA'):Promise<Fixture[]>{const d=await this.request(`${this.fd}/competitions/${competition}/matches`,{'X-Auth-Token':this.credentials.footballDataToken});return (d.matches||[]).map((m:any)=>({id:String(m.id),utcDate:m.utcDate,status:m.status,home:{id:String(m.homeTeam.id),name:m.homeTeam.name},away:{id:String(m.awayTeam.id),name:m.awayTeam.name}}))}
  async standings(competition='SA'):Promise<Standing[]>{const d=await this.request(`${this.fd}/competitions/${competition}/standings`,{'X-Auth-Token':this.credentials.footballDataToken});const total=table(d.standings,'TOTAL'),home=table(d.standings,'HOME'),away=table(d.standings,'AWAY');return [...total.values()].map((r:any)=>({teamId:String(r.team.id),played:r.playedGames,points:r.points,goalsFor:r.goalsFor,goalsAgainst:r.goalsAgainst,formIndex:parseForm(r.form),home:venue(home.get(String(r.team.id))),away:venue(away.get(String(r.team.id)))}))}
  async result(matchId:string){const d=await this.request(`${this.fd}/matches/${encodeURIComponent(matchId)}`,{'X-Auth-Token':this.credentials.footballDataToken,'X-Unfold-Goals':'true'});return {id:String(d.id),status:d.status,home:d.score?.fullTime?.home??null,away:d.score?.fullTime?.away??null,scorers:(d.goals||[]).map((g:any)=>g.scorer?.name||g.player?.name).filter(Boolean),lastUpdated:d.lastUpdated}}
}

export class PredictionApplicationService{
  constructor(private provider:FootballProvider,private store:LocalStore){}
  async predictions(competition='SA',persist=true){const [fixtures,standings]=await Promise.all([this.provider.fixtures(competition),this.provider.standings(competition)]);const byTeam=new Map(standings.map(x=>[x.teamId,x]));const data:PredictionRow[]=fixtures.map(f=>{const h=byTeam.get(f.home.id),a=byTeam.get(f.away.id);if(!h||!a)return {fixture:f,expectedGoalsHome:null,expectedGoalsAway:null,markets:[{market:'MODEL',selection:'NO_BET',probability:0,confidence:0,dataQuality:0,fairOdds:null,status:'NO_BET',reason:'Statistiche mancanti'}],inputs:null};const context:MatchContext={availabilityCoverage:0.75,lineupConfirmed:false,homeAvailabilityLoss:0,awayAvailabilityLoss:0};const bundle=predictFixture(h,a,DEFAULT_MODEL_CONFIG,context);const env=qualityEnvelope(h,a,bundle.markets.filter((m:any)=>m.market==='1X2').map((m:any)=>m.probability),context);return {fixture:f,expectedGoalsHome:bundle.expectedGoalsHome,expectedGoalsAway:bundle.expectedGoalsAway,inputs:{home:h,away:a,availability:{source:'UNAVAILABLE',checked:false}},markets:bundle.markets.map((m:any)=>({...m,confidence:env.confidence,dataQuality:env.dataQuality,status:env.active?'ACTIVE':'NO_BET',reason:env.active?undefined:env.reason}))}});if(persist){const now=new Date().toISOString();for(const row of data)await this.store.savePredictionRun({id:`${row.fixture.id}:${MODEL_VERSION}:${now}`,fixtureId:row.fixture.id,eventAt:row.fixture.utcDate,capturedAt:now,modelVersion:MODEL_VERSION,modelConfigVersion:MODEL_CONFIG_VERSION,inputSnapshot:row.inputs,markets:row.markets})}return {source:'football-data.org',modelVersion:MODEL_VERSION,modelConfigVersion:MODEL_CONFIG_VERSION,data}}
}

export function qualityEnvelope(home:Standing,away:Standing,oneXtwo:number[],context:MatchContext={}){const minGames=Math.min(home.played,away.played),sample=Math.max(0,Math.min(1,minGames/10)),form=home.formIndex==null||away.formIndex==null?0.9:1,venueCoverage=home.home?.played&&away.away?.played?1:0.85,availability=context.availabilityCoverage==null?0.75:Math.max(0.5,Math.min(1,context.availabilityCoverage)),lineup=context.lineupConfirmed?1:0.95,dataQuality=Math.max(0,Math.min(1,sample*form*venueCoverage*availability*lineup)),sorted=[...oneXtwo].sort((a,b)=>b-a),separation=sorted.length>1?sorted[0]-sorted[1]:0,confidence=Math.max(0,Math.min(1,0.45+0.35*dataQuality+0.2*Math.min(1,separation*3))),active=minGames>=3&&dataQuality>=0.6&&confidence>=0.6;return {dataQuality,confidence,active,reason:active?undefined:'Confidence/Data Quality sotto soglia'}}
function table(items:any[],type:string){return new Map<string,any>(((items||[]).find((x:any)=>x.type===type)?.table||[]).map((r:any)=>[String(r.team.id),r]))}
function venue(r:any):VenueMetrics|undefined{return r?{played:Number(r.playedGames||0),points:Number(r.points||0),goalsFor:Number(r.goalsFor||0),goalsAgainst:Number(r.goalsAgainst||0)}:undefined}
function parseForm(value:string|undefined){if(!value)return undefined;const xs=value.split(',').map(x=>x.trim()).filter(Boolean);if(!xs.length)return undefined;return xs.reduce((n,x)=>n+(x==='W'?1:x==='D'?0.5:0),0)/xs.length}
